import express from "express";
import { authenticateToken, requireAdmin } from "../db/middleware.js";
import { pool } from "../db/dbPool.js";
import { apiCache, CACHE_TTL } from "../lib/apiCache.js";

const router = express.Router();

// Public hardcoded admin bootstrap was removed. Production credentials must be provisioned securely.
router.get("/api/admin-setup", (_req, res) => res.status(410).json({ success: false, error: "Admin bootstrap endpoint removed." }));

router.get("/api/admin/settings", async (_req, res) => { try { const k="admin_settings",c=apiCache.get(k); if(c&&Date.now()-c.timestamp<CACHE_TTL)return res.json({success:true,data:c.data}); const r=await pool.query("SELECT * FROM app_settings WHERE id=1"); if(!r.rows.length)return res.json({success:true,data:{}}); apiCache.set(k,{data:r.rows[0],timestamp:Date.now()}); res.json({success:true,data:r.rows[0]}); } catch { res.status(500).json({success:false,error:"Failed to fetch settings"}); } });
router.post("/api/admin/settings", authenticateToken, requireAdmin, async (req,res)=>{ try { const allowed=new Set(["appName","maintenanceMode","supportPhone","supportEmail","privacyUrl","termsUrl"]); const e=Object.entries(req.body||{}).filter(([k])=>allowed.has(k)); if(!e.length)return res.json({success:true}); const q=e.map(([k],i)=>`"${k}"=$${i+1}`).join(","); const r=await pool.query(`UPDATE app_settings SET ${q} WHERE id=1 RETURNING *`,e.map(([,v])=>v)); res.json({success:true,data:r.rows[0]||{}}); } catch { res.status(500).json({success:false,error:"Failed to update settings"}); } });
router.get("/api/admin/announcements", async (_req,res)=>{try{const r=await pool.query("SELECT * FROM announcements ORDER BY created_at DESC");res.json({success:true,data:r.rows})}catch{res.status(500).json({success:false,error:"Failed to fetch announcements"})}});
router.post("/api/admin/announcements",authenticateToken,requireAdmin,async(req,res)=>{try{const {title,content,type,action_url,is_active}=req.body;const r=await pool.query("INSERT INTO announcements (title,content,type,action_url,is_active) VALUES ($1,$2,$3,$4,$5) RETURNING *",[title,content,type||"Urgent Alert",action_url||null,is_active??true]);res.json({success:true,data:r.rows[0]})}catch{res.status(500).json({success:false,error:"Failed to create announcement"})}});
router.delete("/api/admin/announcements/:id",authenticateToken,requireAdmin,async(req,res)=>{try{await pool.query("DELETE FROM announcements WHERE id=$1",[req.params.id]);res.json({success:true})}catch{res.status(500).json({success:false,error:"Failed to delete announcement"})}});
router.put("/api/admin/stories/:id/status",authenticateToken,requireAdmin,async(req,res)=>{try{const {status}=req.body;if(!['pending','approved','rejected'].includes(status))return res.status(400).json({success:false,error:"Invalid status"});const r=await pool.query("UPDATE success_stories SET status=$1 WHERE id=$2 RETURNING *",[status,req.params.id]);res.json({success:true,data:r.rows[0]})}catch{res.status(500).json({success:false,error:"Failed to update story status"})}});
router.get("/api/admin/users",authenticateToken,requireAdmin,async(req,res)=>{try{const page=Math.max(1,parseInt(req.query.page as string)||1),limit=Math.min(100,Math.max(1,parseInt(req.query.limit as string)||50)),offset=(page-1)*limit,c=await pool.query("SELECT COUNT(*) FROM users"),r=await pool.query(`SELECT id,name,role,email,phone,"isVolunteer","isDonor","onboardingCompleted" FROM users ORDER BY id DESC LIMIT $1 OFFSET $2`,[limit,offset]);res.json({success:true,data:r.rows,totalPages:Math.ceil(Number(c.rows[0].count)/limit),currentPage:page})}catch{res.status(500).json({success:false,error:"Failed to fetch users"})}});
router.put("/api/admin/users/:id",authenticateToken,requireAdmin,async(req,res)=>{try{const {name,role,email,phone,isVolunteer,isDonor}=req.body,r=await pool.query(`UPDATE users SET name=$1,role=$2,email=$3,phone=$4,"isVolunteer"=$5,"isDonor"=$6 WHERE id=$7 RETURNING id,name,role,email,phone`,[name,role,email,phone,isVolunteer,isDonor,req.params.id]);res.json({success:true,data:r.rows[0]})}catch{res.status(500).json({success:false,error:"Failed to update user profile"})}});
router.delete("/api/admin/users/:id",authenticateToken,requireAdmin,async(req,res)=>{try{await pool.query("DELETE FROM users WHERE id=$1",[req.params.id]);res.json({success:true})}catch{res.status(500).json({success:false,error:"Failed to delete user"})}});
router.get("/api/admin/volunteers",authenticateToken,requireAdmin,async(req,res)=>{try{const page=Math.max(1,parseInt(req.query.page as string)||1),limit=Math.min(100,Math.max(1,parseInt(req.query.limit as string)||50)),offset=(page-1)*limit,c=await pool.query("SELECT COUNT(*) FROM volunteers"),r=await pool.query(`SELECT id,name,username,mobile,email,status,registration_number,"createdAt" FROM volunteers ORDER BY "createdAt" DESC LIMIT $1 OFFSET $2`,[limit,offset]);res.json({success:true,data:r.rows,totalPages:Math.ceil(Number(c.rows[0].count)/limit),currentPage:page})}catch{res.status(500).json({success:false,error:"Failed to fetch volunteers"})}});
router.put("/api/admin/volunteers/:id/status",authenticateToken,requireAdmin,async(req,res)=>{try{const {status}=req.body;if(!['pending','approved','rejected','suspended'].includes(status))return res.status(400).json({success:false,error:"Invalid volunteer status"});const r=await pool.query("UPDATE volunteers SET status=$1 WHERE id=$2 RETURNING *",[status,req.params.id]);res.json({success:true,data:r.rows[0]})}catch{res.status(500).json({success:false,error:"Failed to update volunteer status"})}});
router.delete("/api/admin/volunteers/:id",authenticateToken,requireAdmin,async(req,res)=>{try{await pool.query("DELETE FROM volunteers WHERE id=$1",[req.params.id]);res.json({success:true})}catch{res.status(500).json({success:false,error:"Failed to delete volunteer"})}});
router.get("/api/admin/donations",authenticateToken,requireAdmin,async(req,res)=>{try{const page=Math.max(1,parseInt(req.query.page as string)||1),limit=Math.min(100,Math.max(1,parseInt(req.query.limit as string)||50)),offset=(page-1)*limit,c=await pool.query("SELECT COUNT(*) FROM donations"),r=await pool.query(`SELECT * FROM donations ORDER BY created_at DESC LIMIT $1 OFFSET $2`,[limit,offset]);res.json({success:true,data:r.rows,totalPages:Math.ceil(Number(c.rows[0].count)/limit),currentPage:page})}catch{res.status(500).json({success:false,error:"Failed to fetch donations"})}});
router.get("/api/admin/jan-seva-cards",authenticateToken,requireAdmin,async(req,res)=>{try{const page=Math.max(1,parseInt(req.query.page as string)||1),limit=Math.min(100,Math.max(1,parseInt(req.query.limit as string)||50)),offset=(page-1)*limit,c=await pool.query("SELECT COUNT(*) FROM card_applications_v2"),r=await pool.query(`SELECT * FROM card_applications_v2 ORDER BY "submittedAt" DESC LIMIT $1 OFFSET $2`,[limit,offset]);res.json({success:true,data:r.rows,totalPages:Math.ceil(Number(c.rows[0].count)/limit),currentPage:page})}catch{res.status(500).json({success:false,error:"Failed to fetch card applications"})}});
router.get("/api/admin/health-camps",authenticateToken,requireAdmin,async(req,res)=>{try{const page=Math.max(1,parseInt(req.query.page as string)||1),limit=Math.min(100,Math.max(1,parseInt(req.query.limit as string)||50)),offset=(page-1)*limit,c=await pool.query("SELECT COUNT(*) FROM health_camps"),r=await pool.query(`SELECT * FROM health_camps ORDER BY date DESC LIMIT $1 OFFSET $2`,[limit,offset]);res.json({success:true,data:r.rows,totalPages:Math.ceil(Number(c.rows[0].count)/limit),currentPage:page})}catch{res.status(500).json({success:false,error:"Failed to fetch health camps"})}});
router.get("/api/admin/grievances",authenticateToken,requireAdmin,async(req,res)=>{try{const page=Math.max(1,parseInt(req.query.page as string)||1),limit=Math.min(100,Math.max(1,parseInt(req.query.limit as string)||50)),offset=(page-1)*limit,c=await pool.query("SELECT COUNT(*) FROM grievances"),r=await pool.query(`SELECT * FROM grievances ORDER BY created_at DESC LIMIT $1 OFFSET $2`,[limit,offset]);res.json({success:true,data:r.rows,totalPages:Math.ceil(Number(c.rows[0].count)/limit),currentPage:page})}catch{res.status(500).json({success:false,error:"Failed to fetch grievances"})}});
router.put("/api/admin/grievances/:id/status",authenticateToken,requireAdmin,async(req,res)=>{try{const {status}=req.body;if(!['Pending','In Progress','Resolved','Rejected'].includes(status))return res.status(400).json({success:false,error:"Invalid grievance status"});const r=await pool.query("UPDATE grievances SET status=$1 WHERE id=$2 RETURNING *",[status,req.params.id]);res.json({success:true,data:r.rows[0]})}catch{res.status(500).json({success:false,error:"Failed to update grievance"})}});

export default router;
