import express from "express";
import { authenticateToken, requireAdmin } from "../db/middleware.js";
import { pool } from "../db/dbPool.js";

const router=express.Router();
const actor=(req:any)=>String(req.user?.id||req.user?.userId||req.user?.email||"");

router.get("/api/metrics",async(_req,res)=>{try{const r=await pool.query("SELECT id,metric_key,label_en,label_hi,value,unit,sort_order,published_at FROM content_metrics WHERE is_published=true ORDER BY sort_order ASC,created_at ASC");res.json({success:true,data:r.rows})}catch{res.status(500).json({success:false,error:"Failed to fetch metrics"})}});
router.get("/api/admin/metrics",authenticateToken,requireAdmin,async(_req,res)=>{try{const r=await pool.query("SELECT * FROM content_metrics ORDER BY updated_at DESC");res.json({success:true,data:r.rows})}catch{res.status(500).json({success:false,error:"Failed to fetch metrics"})}});
router.post("/api/admin/metrics",authenticateToken,requireAdmin,async(req:any,res)=>{try{const a=actor(req);if(!a)return res.status(401).json({success:false,error:"Admin identity required"});const b=req.body||{};if(!String(b.metric_key||"").trim()||!String(b.label_en||"").trim())return res.status(400).json({success:false,error:"metric_key and label_en are required"});const r=await pool.query("INSERT INTO content_metrics(metric_key,label_en,label_hi,value,unit,sort_order,is_published) VALUES($1,$2,$3,$4,$5,$6,false) RETURNING *",[String(b.metric_key).trim(),String(b.label_en).trim(),b.label_hi||null,Number(b.value)||0,b.unit||null,Number(b.sort_order)||0]);res.status(201).json({success:true,data:r.rows[0]})}catch{res.status(500).json({success:false,error:"Failed to create metric"})}});
router.put("/api/admin/metrics/:id",authenticateToken,requireAdmin,async(req,res)=>{try{const b=req.body||{};const r=await pool.query("UPDATE content_metrics SET metric_key=COALESCE($1,metric_key),label_en=COALESCE($2,label_en),label_hi=COALESCE($3,label_hi),value=COALESCE($4,value),unit=COALESCE($5,unit),sort_order=COALESCE($6,sort_order),is_published=false,published_at=NULL,published_by=NULL,updated_at=NOW() WHERE id=$7 RETURNING *",[b.metric_key??null,b.label_en??null,b.label_hi??null,b.value===undefined?null:Number(b.value),b.unit??null,b.sort_order===undefined?null:Number(b.sort_order),req.params.id]);if(!r.rows.length)return res.status(404).json({success:false,error:"Metric not found"});res.json({success:true,data:r.rows[0]})}catch{res.status(500).json({success:false,error:"Failed to update metric"})}});
router.post("/api/admin/metrics/:id/publish",authenticateToken,requireAdmin,async(req:any,res)=>{try{const a=actor(req);if(!a)return res.status(401).json({success:false,error:"Admin identity required"});const r=await pool.query("UPDATE content_metrics SET is_published=true,published_at=NOW(),published_by=$1,updated_at=NOW() WHERE id=$2 RETURNING *",[a,req.params.id]);if(!r.rows.length)return res.status(404).json({success:false,error:"Metric not found"});res.json({success:true,data:r.rows[0]})}catch{res.status(500).json({success:false,error:"Failed to publish metric"})}});
router.post("/api/admin/metrics/:id/unpublish",authenticateToken,requireAdmin,async(req,res)=>{try{const r=await pool.query("UPDATE content_metrics SET is_published=false,published_at=NULL,published_by=NULL,updated_at=NOW() WHERE id=$1 RETURNING *",[req.params.id]);if(!r.rows.length)return res.status(404).json({success:false,error:"Metric not found"});res.json({success:true,data:r.rows[0]})}catch{res.status(500).json({success:false,error:"Failed to unpublish metric"})}});
router.delete("/api/admin/metrics/:id",authenticateToken,requireAdmin,async(req,res)=>{try{const r=await pool.query("DELETE FROM content_metrics WHERE id=$1 RETURNING id",[req.params.id]);if(!r.rows.length)return res.status(404).json({success:false,error:"Metric not found"});res.json({success:true})}catch{res.status(500).json({success:false,error:"Failed to delete metric"})}});
export default router;
