<?php
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: public, max-age=300');
header('Access-Control-Allow-Origin: *');

$cacheFile = __DIR__ . '/rss_cache.json';
$cacheTtl = 300;
if (file_exists($cacheFile) && (time() - filemtime($cacheFile) < $cacheTtl)) { $cached = @file_get_contents($cacheFile); if ($cached && strlen($cached) > 50) { echo $cached; exit; } }

function fetchMultiUrls($urls) { $mh = curl_multi_init(); $handles = []; $results = []; $ua = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'; foreach ($urls as $key => $url) { $ch = curl_init(); curl_setopt_array($ch, [CURLOPT_URL=>$url,CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>true,CURLOPT_MAXREDIRS=>3,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>10,CURLOPT_USERAGENT=>$ua,CURLOPT_HTTPHEADER=>['Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'],CURLOPT_SSL_VERIFYPEER=>true,CURLOPT_SSL_VERIFYHOST=>2,CURLOPT_ENCODING=>'']); curl_multi_add_handle($mh,$ch); $handles[$key]=$ch; } $running=null; do { $status=curl_multi_exec($mh,$running); if($running) curl_multi_select($mh,0.25); } while($running && $status===CURLM_OK); foreach($handles as $key=>$ch){$body=curl_multi_getcontent($ch);$code=curl_getinfo($ch,CURLINFO_HTTP_CODE);$results[$key]=($body!==false&&$code>=200&&$code<300&&strlen($body)>50)?$body:null;curl_multi_remove_handle($mh,$ch);curl_close($ch);} curl_multi_close($mh); return $results; }
function cleanText($text){$text=preg_replace('/<!\[CDATA\[([\s\S]*?)\]\]>/u','$1',$text);$text=html_entity_decode(strip_tags($text),ENT_QUOTES|ENT_HTML5|ENT_XML1,'UTF-8');return preg_replace('/\s+/u',' ',trim($text));}
function parseHtmlLinks($html,$pattern,$source,$baseUrl,$limit=15){if(!$html)return[];$items=[];if(!preg_match_all($pattern,$html,$matches,PREG_SET_ORDER))return[];foreach($matches as $match){$url=isset($match[1])?html_entity_decode(trim($match[1]),ENT_QUOTES|ENT_HTML5,'UTF-8'):'';$title=isset($match[2])?cleanText($match[2]):'';if(mb_strlen($title)<15)continue;if(stripos($title,'latest news')!==false||stripos($title,'copyright')!==false||stripos($title,'skip to content')!==false)continue;if($url!==''&&!preg_match('#^https?://#i',$url))$url=rtrim($baseUrl,'/').'/'.ltrim($url,'/');$key=mb_strtolower($source.'|'.$title,'UTF-8');if(isset($items[$key]))continue;$items[$key]=['title'=>$title,'source'=>$source,'url'=>$url,'publishedAt'=>''];if(count($items)>=$limit)break;}return array_values($items);}
function parseSachetItems($xml,$limit=30){if(!$xml)return[];$items=[];if(!preg_match_all('/<(?:item|entry)\b[\s\S]*?<\/(?:item|entry)>/iu',$xml,$blocks))return[];foreach($blocks[0] as $block){if(!preg_match('/<title(?:\s[^>]*)?>([\s\S]*?)<\/title>/iu',$block,$m))continue;$title=cleanText($m[1]);if(mb_strlen($title)<8)continue;$link='';if(preg_match('/<link>([\s\S]*?)<\/link>/iu',$block,$m))$link=cleanText($m[1]);elseif(preg_match('/<link[^>]+href=["\']([^"\']+)["\']/iu',$block,$m))$link=trim($m[1]);$published='';if(preg_match('/<(?:pubDate|published|updated)>([\s\S]*?)<\/(?:pubDate|published|updated)>/iu',$block,$m))$published=cleanText($m[1]);$key=mb_strtolower($title,'UTF-8');if(isset($items[$key]))continue;$items[$key]=['title'=>$title,'source'=>'','url'=>$link,'publishedAt'=>$published];if(count($items)>=$limit)break;}return array_values($items);}

$raw=fetchMultiUrls(['pib'=>'https://www.pib.gov.in/allRel.aspx?reg=48&lang=2','ani'=>'https://www.aninews.in/latest-news/','sachet'=>'https://sachet.ndma.gov.in/cap_public_website/rss/rss_india.xml']);
// HTML is intentionally primary for the newest PIB and ANI updates; RSS was previously delayed.
$pib=parseHtmlLinks($raw['pib']??'','/<a\b[^>]*(?:href=["\']([^"\']*(?:PRID=[0-9]+|ReleaseSimpleHtml)[^"\']*)["\'])[^>]*>([\s\S]*?)<\/a>/iu','PIB','https://www.pib.gov.in',15);
$ani=parseHtmlLinks($raw['ani']??'','/<a\b[^>]*href=["\']([^"\']*\/news\/[^"\']*)["\'][^>]*>([\s\S]*?)<\/a>/iu','ANI','https://www.aninews.in',15);
$news=[];$seen=[];$max=max(count($pib),count($ani));for($i=0;$i<$max&&count($news)<30;$i++){foreach([$pib[$i]??null,$ani[$i]??null] as $item){if(!$item)continue;$key=mb_strtolower($item['source'].'|'.$item['title'],'UTF-8');if(isset($seen[$key]))continue;$seen[$key]=true;$news[]=$item;}}
$sachet=parseSachetItems($raw['sachet']??'',30);
if((!$news||!$sachet)&&file_exists($cacheFile)){$old=json_decode((string)@file_get_contents($cacheFile),true);if(is_array($old)&&isset($old['data'])){if(!$news&&!empty($old['data']['news']))$news=$old['data']['news'];if(!$sachet&&!empty($old['data']['sachet']))$sachet=$old['data']['sachet'];}}
$response=['success'=>!empty($news)||!empty($sachet),'data'=>['pib'=>$news,'news'=>$news,'sachet'=>$sachet],'updatedAt'=>gmdate('c')];@file_put_contents($cacheFile,json_encode($response,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));echo json_encode($response,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
