import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { useAuth } from '../../context/AuthContext';
import FileUpload from '../FileUpload';
import { CmsConfig } from '../../context/AppContext';
import { LIVE_TV_DEFAULTS, type LiveTvChannel } from '../../data/liveTvDefaults';
import rawRadioStations from '../../data/akashvaniChannels.json';
import { Save, User, Quote, FileText, Tv, Radio } from 'lucide-react';
import { Skeleton } from '../ui/Skeleton';

type RadioStation = { name: string; url: string; image: string; page: string; enabled?: boolean; order?: number };
const RADIO_DEFAULTS = rawRadioStations as RadioStation[];
const validRadio = (value: unknown): value is RadioStation[] => Array.isArray(value) && value.every((s: any) => s && typeof s.name === 'string' && typeof s.url === 'string');

export const CmsSettings = () => {
  const { token } = useAuth();
  const [cms, setCms] = useState<CmsConfig | null>(null);
  const [loading, setLoading] = useState(true), [saving, setSaving] = useState(false);
  const [channelError, setChannelError] = useState(''), [channelText, setChannelText] = useState('[]');
  const [radioError, setRadioError] = useState(''), [radioText, setRadioText] = useState('[]');
  useEffect(() => { axios.get('/api/cms').then(res => { if (res.data.success) { const next=res.data.cms; setCms(next); setChannelText(JSON.stringify(Array.isArray(next.liveTvChannels)?next.liveTvChannels:[],null,2)); setRadioText(JSON.stringify(validRadio(next.internetRadioStations)?next.internetRadioStations:[],null,2)); } }).catch(()=>undefined).finally(()=>setLoading(false)); }, []);
  const set = (key:string,value:unknown) => setCms(current => current ? { ...(current as any), [key]:value } : current);
  const channels = Array.isArray((cms as any)?.liveTvChannels) ? (cms as any).liveTvChannels as LiveTvChannel[] : [];
  const radios = validRadio((cms as any)?.internetRadioStations) ? (cms as any).internetRadioStations as RadioStation[] : [];
  const save = async () => { if (!cms || channelError || radioError) return; setSaving(true); try { await axios.post('/api/cms', cms, { headers:{Authorization:`Bearer ${token}`} }); } finally { setSaving(false); } };
  const updateChannels=(raw:string)=>{setChannelText(raw);try{const parsed=JSON.parse(raw);if(!Array.isArray(parsed))throw new Error();set('liveTvChannels',parsed);setChannelError('')}catch{setChannelError('Channel list must be a valid JSON array before saving.')}};
  const updateRadio=(raw:string)=>{setRadioText(raw);try{const parsed=JSON.parse(raw);if(!validRadio(parsed))throw new Error();set('internetRadioStations',parsed);setRadioError('')}catch{setRadioError('Radio list must be a valid JSON array and every station needs at least name and url.')}};
  const loadDefaults=()=>{set('liveTvChannels',LIVE_TV_DEFAULTS);setChannelText(JSON.stringify(LIVE_TV_DEFAULTS,null,2));setChannelError('')};
  const clearChannels=()=>{set('liveTvChannels',[]);setChannelText('[]');setChannelError('')};
  const loadRadioDefaults=()=>{set('internetRadioStations',RADIO_DEFAULTS);setRadioText(JSON.stringify(RADIO_DEFAULTS,null,2));setRadioError('')};
  const clearRadio=()=>{set('internetRadioStations',[]);setRadioText('[]');setRadioError('')};
  if(loading||!cms)return <div className="space-y-4"><Skeleton className="h-10"/><Skeleton className="h-[220px]"/></div>;
  return <div className="max-w-4xl space-y-5 pb-20">
    <div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-slate-400">Content only</p><h2 className="mt-1 text-xl font-black">Foundation content</h2><p className="mt-1 text-xs text-slate-500">Content changes are served from the CMS. Native Android changes still require a new APK.</p></div><button onClick={save} disabled={saving||!!channelError||!!radioError} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-xs font-bold text-white disabled:opacity-50"><Save className="h-4 w-4"/>{saving?'Saving…':'Save changes'}</button></div>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="flex items-center gap-2 text-sm font-black"><FileText className="h-4 w-4"/>General information</h3><div className="mt-4 grid gap-4"><FileUpload label="Site logo" defaultUrl={cms.logoImgUrl||''} onUploadSuccess={url=>set('logoImgUrl',url)}/><div><label className="text-xs font-bold text-slate-600">About content</label><textarea value={cms.aboutTextEn||''} onChange={e=>set('aboutTextEn',e.target.value)} rows={4} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none"/></div></div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="flex items-center gap-2 text-sm font-black"><Tv className="h-4 w-4"/>Live TV remote control</h3><p className="mt-1 text-xs text-slate-500">Add, remove, disable, rename, recategorize or reorder channels. No APK rebuild is needed for channel changes.</p><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={loadDefaults} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold">Load current default channels ({LIVE_TV_DEFAULTS.length})</button><button type="button" onClick={clearChannels} className="rounded-xl border border-rose-200 px-3 py-2 text-xs font-bold text-rose-700">Clear all</button><span className="self-center text-[11px] text-slate-400">Configured: {channels.length}</span></div><label className="mt-4 block text-xs font-bold text-slate-600">Channel JSON</label><textarea value={channelText} onChange={e=>updateChannels(e.target.value)} rows={14} spellCheck={false} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-slate-950 px-3 py-3 font-mono text-xs text-slate-100 outline-none"/>{channelError&&<p className="mt-2 text-xs font-semibold text-rose-600">{channelError}</p>}</section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="flex items-center gap-2 text-sm font-black"><Radio className="h-4 w-4"/>Internet Radio remote control</h3><p className="mt-1 text-xs text-slate-500">The complete bundled station list is preserved as a safe fallback. Load the current list once, save it to the CMS, then add, remove, disable, edit or reorder stations without an APK rebuild.</p><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={loadRadioDefaults} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold">Load current bundled stations ({RADIO_DEFAULTS.length})</button><button type="button" onClick={clearRadio} className="rounded-xl border border-rose-200 px-3 py-2 text-xs font-bold text-rose-700">Clear all</button><span className="self-center text-[11px] text-slate-400">Configured: {radios.length}</span></div><label className="mt-4 block text-xs font-bold text-slate-600">Station JSON</label><textarea value={radioText} onChange={e=>updateRadio(e.target.value)} rows={18} spellCheck={false} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-slate-950 px-3 py-3 font-mono text-xs text-slate-100 outline-none"/>{radioError&&<p className="mt-2 text-xs font-semibold text-rose-600">{radioError}</p>}<p className="mt-2 text-[11px] text-slate-500">Each station needs name and url. Optional: image, page, enabled and order. Set enabled:false to hide without deleting.</p></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="flex items-center gap-2 text-sm font-black"><User className="h-4 w-4"/>Founder profile</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><input value={cms.founderName||''} onChange={e=>set('founderName',e.target.value)} placeholder="Founder name" className="rounded-xl border border-slate-200 px-3 py-3 text-sm"/><input value={cms.founderDesignation||''} onChange={e=>set('founderDesignation',e.target.value)} placeholder="Designation" className="rounded-xl border border-slate-200 px-3 py-3 text-sm"/><div className="sm:col-span-2"><FileUpload label="Founder image" defaultUrl={cms.founderImgUrl||''} onUploadSuccess={url=>set('founderImgUrl',url)}/></div></div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="flex items-center gap-2 text-sm font-black"><Quote className="h-4 w-4"/>Optional messaging</h3><div className="mt-4 grid gap-4"><textarea value={cms.quoteOfTheDayEn||''} onChange={e=>set('quoteOfTheDayEn',e.target.value)} rows={3} className="w-full rounded-xl border border-slate-200 px-3 py-3 text-sm"/><textarea value={cms.impactBottomTextEn||''} onChange={e=>set('impactBottomTextEn',e.target.value)} rows={3} className="w-full rounded-xl border border-slate-200 px-3 py-3 text-sm"/></div></section>
  </div>;
};
