import React,{useMemo,useState}from"react";import{Calculator,ChevronRight,HeartPulse,Wallet,Brain,Clock3,Ruler,House,Wifi,CloudSun,Car,Smile,Search}from"lucide-react";import{useNavigate}from"react-router-dom";import Shell from"./UtilityPageShell";

type Item={id:string;title:string;desc:string};type Group={id:string;title:string;icon:any;items:Item[]};
const groups:Group[]=[
{id:"health",title:"Health & Fitness",icon:HeartPulse,items:["BMI Calculator","Calorie Calculator","Body Fat Calculator","BMR Calculator","Ideal Weight Calculator","Pace Calculator","Lean Body Mass Calculator","Healthy Weight Calculator","Calories Burned Calculator","One Rep Max Calculator","Target Heart Rate Calculator","Macro Calculator","Protein Calculator","TDEE Calculator","Body Surface Area Calculator","GFR / eGFR Calculator","Pregnancy Calculator","Due Date Calculator","Ovulation Calculator","Period Calculator","Sleep Health Calculator","Blood Pressure Analyzer","Heart Risk Calculator","Diabetes Risk Score","HbA1c Converter","Body Age Calculator","IT Employee Health Risk"].map(x=>({id:x.toLowerCase().replace(/[^a-z0-9]+/g,"-"),title:x,desc:"Private, on-device health awareness tool"}))},
{id:"finance",title:"Financial Calculators",icon:Wallet,items:["Mortgage Calculator","Loan Calculator","Auto Loan Calculator","Interest Calculator","Investment Calculator","Compound Interest Calculator","Savings Calculator","Retirement Calculator","Pension Calculator","Annuity Calculator","Income Tax Calculator","Salary Calculator","Take-Home Pay Calculator","Currency Calculator","Inflation Calculator","Credit Card Calculator","Debt Payoff Calculator","Student Loan Calculator","VAT Calculator","Depreciation Calculator","Margin Calculator","Discount Calculator","Business Loan Calculator","Personal Loan Calculator","Budget Calculator","Commission Calculator","ROI Calculator","IRR Calculator","Future Value Calculator","Present Value Calculator"].map(x=>({id:x.toLowerCase().replace(/[^a-z0-9]+/g,"-"),title:x,desc:"Financial planning calculator"}))},
{id:"math",title:"Math & Science",icon:Brain,items:["Scientific Calculator","Fraction Calculator","Percentage Calculator","Random Number Generator","Percent Error Calculator","Exponent Calculator","Binary Calculator","Hex Calculator","Half-Life Calculator","Quadratic Formula Calculator","Log Calculator","Ratio Calculator","Root Calculator","LCM Calculator","GCF Calculator","Factor Calculator","Rounding Calculator","Matrix Calculator","Scientific Notation Calculator","Big Number Calculator","Standard Deviation Calculator","Probability Calculator","Statistics Calculator","Mean Median Mode Range","Permutation & Combination","Z-Score Calculator","Confidence Interval Calculator","Triangle Calculator","Volume Calculator","Slope Calculator","Area Calculator","Distance Calculator","Circle Calculator","Surface Area Calculator","Pythagorean Theorem","Right Triangle Calculator"].map(x=>({id:x.toLowerCase().replace(/[^a-z0-9]+/g,"-"),title:x,desc:"Math and science utility"}))},
{id:"date",title:"Date & Time",icon:Clock3,items:["Age Calculator","Date Calculator","Time Calculator","Hours Calculator","Time Card Calculator","Time Zone Calculator","Time Duration Calculator","Day Counter","Day of the Week Calculator"].map(x=>({id:x.toLowerCase().replace(/[^a-z0-9]+/g,"-"),title:x,desc:"Date and time calculation"}))},
{id:"home",title:"Home & Building",icon:House,items:["Concrete Calculator","BTU Calculator","Square Footage Calculator","Stair Calculator","Roofing Calculator","Tile Calculator","Mulch Calculator","Gravel Calculator"].map(x=>({id:x.toLowerCase().replace(/[^a-z0-9]+/g,"-"),title:x,desc:"Home and construction estimate"}))},
{id:"measure",title:"Measurements & Units",icon:Ruler,items:["Height Calculator","Conversion Calculator","GDP Calculator","Density Calculator","Mass Calculator","Weight Calculator","Speed Calculator","Molarity Calculator","Molecular Weight Calculator","Roman Numeral Converter"].map(x=>({id:x.toLowerCase().replace(/[^a-z0-9]+/g,"-"),title:x,desc:"Measurement and conversion tool"}))},
{id:"internet",title:"Internet Tools",icon:Wifi,items:["IP Subnet Calculator","Password Generator","Bandwidth Calculator","Base64 Encode / Decode","URL Encode / Decode"].map(x=>({id:x.toLowerCase().replace(/[^a-z0-9]+/g,"-"),title:x,desc:"Useful offline internet utility"}))},
{id:"weather",title:"Weather",icon:CloudSun,items:["Wind Chill Calculator","Heat Index Calculator","Dew Point Calculator"].map(x=>({id:x.toLowerCase().replace(/[^a-z0-9]+/g,"-"),title:x,desc:"Weather calculation"}))},
{id:"transport",title:"Transportation",icon:Car,items:["Fuel Cost Calculator","Gas Mileage Calculator","Horsepower Calculator","Engine Horsepower Calculator","Mileage Calculator","Tire Size Calculator"].map(x=>({id:x.toLowerCase().replace(/[^a-z0-9]+/g,"-"),title:x,desc:"Vehicle and travel calculation"}))},
{id:"everyday",title:"Everyday Utility",icon:Smile,items:["GPA Calculator","Grade Calculator","Shoe Size Conversion","Tip Calculator","Golf Handicap Calculator","Sleep Calculator","GST Calculator","Split Bill"].map(x=>({id:x.toLowerCase().replace(/[^a-z0-9]+/g,"-"),title:x,desc:"Everyday quick calculation"}))},
];
export default function CalculatorCenterPage(){const n=useNavigate(),[q,setQ]=useState(""),[cat,setCat]=useState("all");const filtered=useMemo(()=>groups.map(g=>({...g,items:g.items.filter(i=>(cat==="all"||cat===g.id)&&(!q||i.title.toLowerCase().includes(q.toLowerCase())))})).filter(g=>g.items.length),[q,cat]);const open=(id:string)=>{if(id==="bmi-calculator")return n("/utilities/bmi-calculator");if(id==="gst-calculator")return n("/utilities/gst-calculator");if(id==="split-bill")return n("/utilities/split-bill");n(`/utilities/calculator-tool/${id}`)};return <Shell title="Calculator Center" icon={<Calculator className="h-4 w-4"/>} onBack={()=>n("/utilities")}><div className="space-y-4"><div className="relative"><Search className="absolute left-3 top-3.5 h-4 w-4 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search any calculator..." className="w-full rounded-xl border p-3 pl-10"/></div><div className="flex gap-2 overflow-x-auto pb-1">{[["all","All"],...groups.map(g=>[g.id,g.title] as const)].map(([id,title])=><button key={id} onClick={()=>setCat(id)} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-black ${cat===id?"bg-[#000080] text-white":"bg-slate-100 text-slate-600"}`}>{title}</button>)}</div>{filtered.map(g=>{const Icon=g.icon;return <section key={g.id}><div className="mb-2 flex items-center gap-2"><Icon className="h-4 w-4 text-[#000080]"/><h2 className="font-black text-slate-800">{g.title}</h2><span className="text-xs text-slate-400">{g.items.length}</span></div><div className="grid gap-2 sm:grid-cols-2">{g.items.map(i=><button key={i.id} onClick={()=>open(i.id)} className="flex items-center gap-3 rounded-xl border border-slate-100 bg-slate-50 p-3 text-left hover:bg-white"><div className="flex-1"><div className="text-sm font-bold text-slate-800">{i.title}</div><div className="text-[11px] text-slate-500">{i.desc}</div></div><ChevronRight className="h-4 w-4 text-slate-300"/></button>)}</div></section>})}<p className="rounded-xl bg-amber-50 p-3 text-xs leading-relaxed text-amber-800">Health calculators are for awareness and estimation only. They do not diagnose disease or replace a qualified healthcare professional. Results should be interpreted with appropriate clinical context.</p></div></Shell>}
