import React,{useMemo,useState}from"react";
import{Calculator,ChevronRight,HeartPulse,Wallet,Brain,Clock3,Ruler,House,Wifi,CloudSun,Car,Smile,Search,Star,ArrowLeft}from"lucide-react";
import{useNavigate}from"react-router-dom";
import Shell from"./UtilityPageShell";

type Item={id:string;title:string;desc:string};type Group={id:string;title:string;icon:any;items:Item[]};
const make=(xs:string[],desc:string)=>Array.from(new Map(xs.map(x=>{const id=x.toLowerCase().replace(/[^a-z0-9]+/g,"-");return[id,{id,title:x,desc}]})).values());
const groups:Group[]=[
{id:"health",title:"Health & Fitness",icon:HeartPulse,items:make(["BMI Calculator","Calorie Calculator","Body Fat Calculator","BMR Calculator","Ideal Weight Calculator","Pace Calculator","Lean Body Mass Calculator","Healthy Weight Calculator","Calories Burned Calculator","One Rep Max Calculator","Target Heart Rate Calculator","Macro Calculator","Protein Calculator","TDEE Calculator","Body Surface Area Calculator","GFR / eGFR Calculator","Pregnancy Calculator","Due Date Calculator","Ovulation Calculator","Period Calculator","Sleep Health Calculator","Blood Pressure Analyzer","Heart Risk Calculator","Diabetes Risk Score","HbA1c Converter","Body Age Calculator","IT Employee Health Risk","Water Intake Calculator","Waist-to-Height Ratio","Army Body Fat Calculator"],"Private, on-device health awareness tool")},
{id:"medical",title:"Medical & Blood Reports",icon:HeartPulse,items:make(["Lab Result Checker","CBC Hemoglobin Calculator","CBC Hematocrit Calculator","RBC Count Calculator","WBC Count Calculator","Platelet Calculator","MCV Calculator","MCH Calculator","MCHC Calculator","RDW Calculator","ANC Calculator","NLR Calculator","Total Cholesterol Checker","LDL Calculator","Non-HDL Cholesterol Calculator","Cholesterol Ratio Calculator","Triglyceride / HDL Ratio","Triglyceride Checker","HDL Checker","AST/ALT Ratio Calculator","ALT Checker","AST Checker","Albumin / Globulin Ratio","Bilirubin Checker","Albumin Checker","ALP Checker","GGT Checker","BUN Calculator","BUN / Creatinine Ratio","Creatinine Clearance Calculator","Uric Acid Checker","Urine ACR Calculator","Anion Gap Calculator","Corrected Sodium Calculator","Serum Osmolality Calculator","Corrected Calcium Calculator","Iron Saturation Calculator"],"CBC, lipid, KFT, LFT, electrolytes and lab awareness")},
{id:"medical2",title:"Medical Tests & Profiles",icon:HeartPulse,items:make(["TSH Checker","Free T4 Checker","Free T3 Checker","Ferritin Checker","Vitamin B12 Checker","Vitamin D Checker","CRP Checker","ESR Checker","PT / INR Calculator","aPTT Checker","Fibrinogen Checker","Amylase Checker","Lipase Checker","LDH Checker","Magnesium Checker","Phosphate Checker","Potassium Checker","Sodium Checker","Chloride Checker","Fasting Glucose Checker","Random Glucose Checker","Urine Protein Checker","PSA Checker","CEA Checker","AFP Checker"],"Thyroid, vitamins, inflammation, coagulation and other tests")},
{id:"finance",title:"Financial Calculators",icon:Wallet,items:make(["Mortgage Calculator","Loan Calculator","Auto Loan Calculator","Interest Calculator","Investment Calculator","Compound Interest Calculator","Savings Calculator","Retirement Calculator","Pension Calculator","Annuity Calculator","Income Tax Calculator","Salary Calculator","Take-Home Pay Calculator","Currency Calculator","Inflation Calculator","Credit Card Calculator","Debt Payoff Calculator","Student Loan Calculator","VAT Calculator","Depreciation Calculator","Margin Calculator","Discount Calculator","Business Loan Calculator","Personal Loan Calculator","Budget Calculator","Commission Calculator","ROI Calculator","IRR Calculator","Future Value Calculator","Present Value Calculator","EMI Calculator","SIP Calculator","PPF Calculator","GST Calculator","GST Inclusive Calculator","GST Split Calculator","FD Calculator","RD Calculator","NPS Calculator","EPF Calculator","Simple Interest Calculator","CAGR Calculator","Break-Even Calculator"],"India-friendly financial planning")},
{id:"math",title:"Math & Science",icon:Brain,items:make(["Scientific Calculator","Fraction Calculator","Percentage Calculator","Random Number Generator","Percent Error Calculator","Exponent Calculator","Binary Calculator","Hex Calculator","Half-Life Calculator","Quadratic Formula Calculator","Log Calculator","Ratio Calculator","Root Calculator","LCM Calculator","GCF Calculator","Factor Calculator","Rounding Calculator","Matrix Calculator","Scientific Notation Calculator","Big Number Calculator","Standard Deviation Calculator","Probability Calculator","Statistics Calculator","Mean Median Mode Range","Permutation & Combination","Z-Score Calculator","Confidence Interval Calculator","Triangle Calculator","Volume Calculator","Slope Calculator","Area Calculator","Distance Calculator","Circle Calculator","Surface Area Calculator","Pythagorean Theorem","Right Triangle Calculator","Cube Calculator","Cylinder Calculator","Sphere Calculator","Cone Calculator","Percent Change Calculator"],"Math and science tools")},
{id:"date",title:"Date & Time",icon:Clock3,items:make(["Age Calculator","Date Calculator","Time Calculator","Hours Calculator","Time Card Calculator","Time Zone Calculator","Time Duration Calculator","Day Counter","Day of the Week Calculator","Business Days Calculator","Date Difference Calculator","Countdown Calculator"],"Dates, age and time")},
{id:"home",title:"Home & Building",icon:House,items:make(["Concrete Calculator","BTU Calculator","Square Footage Calculator","Stair Calculator","Roofing Calculator","Tile Calculator","Mulch Calculator","Gravel Calculator","Paint Calculator","Flooring Calculator","Brick Calculator","Wall Area Calculator","Room Volume Calculator"],"Home and construction estimates")},
{id:"measure",title:"Measurements & Units",icon:Ruler,items:make(["Height Calculator","Conversion Calculator","GDP Calculator","Density Calculator","Mass Calculator","Weight Calculator","Speed Calculator","Molarity Calculator","Molecular Weight Calculator","Roman Numeral Converter","Temperature Converter","Length Converter","Area Converter","Volume Converter","Time Converter","Pressure Converter","Energy Converter","Power Converter","Data Storage Converter","BMI Unit Converter"],"Conversions and measurements")},
{id:"internet",title:"Internet Tools",icon:Wifi,items:make(["Password Generator","Bandwidth Calculator","Base64 Encode / Decode","URL Encode / Decode","IPv4 Converter","Data Transfer Time Calculator","Hash Length Calculator"],"Useful offline internet utilities")},
{id:"weather",title:"Weather",icon:CloudSun,items:make(["Wind Chill Calculator","Heat Index Calculator","Dew Point Calculator","Relative Humidity Calculator","Temperature Conversion","Wind Speed Conversion"],"Weather calculations")},
{id:"transport",title:"Transportation",icon:Car,items:make(["Fuel Cost Calculator","Gas Mileage Calculator","Horsepower Calculator","Engine Horsepower Calculator","Mileage Calculator","Tire Size Calculator","Trip Cost Calculator","Travel Time Calculator","Fuel Consumption Converter","EV Charging Cost Calculator"],"Vehicle and travel calculations")},
{id:"everyday",title:"Everyday Utility",icon:Smile,items:make(["GPA Calculator","Grade Calculator","Shoe Size Conversion","Tip Calculator","Golf Handicap Calculator","Sleep Calculator","Split Bill","Age in Days Calculator","Cooking Unit Converter"],"Quick everyday calculations")},
{id:"education",title:"Education",icon:Brain,items:make(["Percentage of Number Calculator","Grade Percentage Calculator","Attendance Calculator","CGPA to Percentage Calculator"],"Marks, grades and study calculations")},
{id:"agriculture",title:"Agriculture",icon:House,items:make(["Crop Seed Rate Calculator","Fertilizer Requirement Calculator","Irrigation Water Calculator"],"Simple farm planning estimates")},
{id:"electrical",title:"Electrical & Engineering",icon:Wifi,items:make(["Electricity Bill Calculator","Power Consumption Calculator","Ohms Law Calculator","Resistor Calculator"],"Practical electrical calculations")},
{id:"itnetwork",title:"IT & Networking",icon:Wifi,items:make(["Data Usage Calculator","Subnet Host Calculator"],"Data, network and internet calculations")},
{id:"construction",title:"Construction",icon:House,items:make(["Concrete Volume Calculator","Brick Quantity Calculator","Paint Quantity Calculator"],"Basic construction material estimates")}
];
const popular=["BMI Calculator","EMI Calculator","GST Calculator","Income Tax Calculator","SIP Calculator","Age Calculator"].map(title=>({title,id:title.toLowerCase().replace(/[^a-z0-9]+/g,"-")}));
export default function CalculatorCenterPage(){
 const n=useNavigate(),[q,setQ]=useState(""),[cat,setCat]=useState("all");
 const selected=groups.find(g=>g.id===cat);
 const results=useMemo(()=>groups.flatMap(g=>g.items).filter(i=>!q||i.title.toLowerCase().includes(q.toLowerCase())),[q]);
 const open=(id:string)=>n("/utilities/calculator-tool/"+id);
 const category=(g:Group)=>{const Icon=g.icon;const tones:{[key:string]:string}={health:"bg-emerald-50 text-emerald-700",medical:"bg-blue-50 text-blue-700",medical2:"bg-violet-50 text-violet-700",finance:"bg-amber-50 text-amber-700",math:"bg-indigo-50 text-indigo-700",date:"bg-sky-50 text-sky-700",home:"bg-orange-50 text-orange-700",measure:"bg-teal-50 text-teal-700",internet:"bg-cyan-50 text-cyan-700",weather:"bg-yellow-50 text-yellow-700",transport:"bg-rose-50 text-rose-700",everyday:"bg-pink-50 text-pink-700"};const tone=tones[g.id]||"bg-slate-50 text-slate-700";return <button type="button" key={g.id} onClick={()=>{setCat(g.id);setQ("")}} className="group flex min-h-[118px] flex-col rounded-2xl border border-slate-100 bg-white p-3.5 text-left shadow-[0_2px_10px_rgba(15,23,42,.045)] transition active:scale-[.985] hover:-translate-y-0.5 hover:shadow-[0_6px_18px_rgba(15,23,42,.07)]"><div className="flex items-start justify-between"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${tone}`}><Icon className="h-5 w-5"/></span><ChevronRight className="mt-1 h-4 w-4 text-slate-300 transition group-hover:translate-x-0.5 group-hover:text-slate-500"/></div><div className="mt-2.5 min-w-0"><div className="line-clamp-2 text-[14px] font-bold leading-[18px] tracking-tight text-slate-800">{g.title}</div><div className="mt-1 text-[11px] font-medium text-slate-400">{g.items.length} tools</div></div></button>};
 const card=(i:Item)=> <button type="button" key={i.id} onClick={()=>open(i.id)} className="group flex min-h-20 items-center gap-3 rounded-2xl border border-slate-100 bg-white p-3.5 text-left shadow-[0_3px_14px_rgba(15,23,42,.05)] transition active:scale-[.99] hover:shadow-md"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#f0f8f5]"><Calculator className="h-5 w-5 text-[#167C5A]"/></span><span className="min-w-0 flex-1"><span className="block text-[13px] font-bold text-slate-800">{i.title}</span><span className="mt-0.5 block text-[10px] leading-4 text-slate-400">{i.desc}</span></span><ChevronRight className="h-4 w-4 shrink-0 text-slate-300"/></button>;

 const handleBack = () => {
   if (window.history.length > 1) {
     n(-1);
   } else {
     n("/utilities");
   }
 };

 return <Shell title="Calculator Center" icon={<Calculator className="h-4 w-4"/>} onBack={handleBack}><div className="space-y-5">
  <div className="rounded-2xl bg-gradient-to-r from-[#fff7e8] to-[#f3f8ff] p-4"><div className="text-xl font-extrabold tracking-tight text-slate-800">Find the right calculator</div><div className="mt-1 text-xs leading-5 text-slate-500">Search directly, or choose a category below. Everything runs inside the app.</div></div>
  <div className="relative"><Search className="absolute left-4 top-3.5 h-5 w-5 text-slate-400"/><input value={q} onChange={e=>{setQ(e.target.value);if(e.target.value)setCat("all")}} placeholder="Search calculator..." className="w-full rounded-2xl border border-slate-200 bg-white p-3.5 pl-12 text-sm outline-none shadow-[0_4px_16px_rgba(15,23,42,.05)] focus:border-[#167C5A] focus:ring-2 focus:ring-[#167C5A]/10"/></div>
  {q?<section><div className="mb-3 flex items-center justify-between"><h2 className="font-black text-slate-800">Search results</h2><span className="text-xs text-slate-400">{results.length}</span></div><div className="grid gap-3 sm:grid-cols-2">{results.map(card)}</div></section>:
   cat==="all"?<><section><div className="mb-3 flex items-center gap-2"><Star className="h-4 w-4 text-[#d28a00]"/><h2 className="font-black text-slate-800">Popular calculators</h2></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{popular.map(p=>{const found=groups.flatMap(g=>g.items).find(i=>i.id===p.id)||{id:p.id,title:p.title,desc:"Quick calculator"};return card(found)})}</div></section><section><div className="mb-3"><h2 className="text-[17px] font-extrabold tracking-tight text-slate-800">Categories</h2><p className="mt-0.5 text-xs text-slate-400">Choose a category to continue.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{groups.map(category)}</div></section></>:
   <section><button type="button" onClick={()=>setCat("all")} className="mb-3 inline-flex items-center gap-1 text-xs font-bold text-[#167C5A]"><ArrowLeft className="h-4 w-4"/>All categories</button><div className="mb-3 flex items-end justify-between"><div><h2 className="font-black text-slate-800">{selected?.title}</h2><p className="text-xs text-slate-400">{selected?.items.length} calculators</p></div></div><div className="grid gap-3 sm:grid-cols-2">{selected?.items.map(card)}</div></section>}
  <p className="rounded-2xl bg-amber-50 p-3 text-xs leading-relaxed text-amber-800">Health calculators are for awareness and estimation only. They do not diagnose disease or replace a qualified healthcare professional.</p>
 </div></Shell>
}