import { useEffect, useState } from "react";
import { ArrowRight, CloudSun, HeartPulse, Newspaper, Radio, Sparkles, Wind } from "lucide-react";
import { useNavigate, useOutletContext } from "react-router-dom";
type Lang="en"|"hi";type WeatherState={temperature:number;apparent:number;humidity:number;wind:number;aqi:number|null};
const WAQI_TOKEN="83274cc3f5749b4ec7b5b6c7b9f40464debbd6b1";
const cards=[{id:"news",icon:Newspaper,titleEn:"News",titleHi:"समाचार",descEn:"Stay informed with current stories.",descHi:"ताज़ा समाचार और महत्वपूर्ण जानकारी।",route:"/news",tone:"indigo"},{id:"culture",icon:Sparkles,titleEn:"Culture & Spirituality",titleHi:"संस्कृति और अध्यात्म",descEn:"Festivals, calendar and cultural content.",descHi:"त्योहार, कैलेंडर और सांस्कृतिक जानकारी।",route:"/culture",tone:"saffron"},{id:"health",icon:HeartPulse,titleEn:"Health Hub",titleHi:"स्वास्थ्य केंद्र",descEn:"Health information and community care.",descHi:"स्वास्थ्य जानकारी और सामुदायिक सहायता।",route:"/health-care",tone:"rose"},{id:"radio",icon:Radio,titleEn:"Radio",titleHi:"रेडियो",descEn:"Listen to the available live stream.",descHi:"उपलब्ध लाइव रेडियो स्ट्रीम सुनें।",route:"/internet-radio",tone:"green"}];
const tones:Record<string,string>={indigo:"bg-indigo-50 text-indigo-700 ring-indigo-100",saffron:"bg-orange-50 text-orange-700 ring-orange-100",rose:"bg-rose-50 text-rose-700 ring-rose-100",green:"bg-emerald-50 text-emerald-700 ring-emerald-100"};
export default function DailyHub(){const {lang}=useOutletContext<{lang:Lang}>();const navigate=useNavigate();const[weather,setWeather]=useState<WeatherState|null>(null);const[place,setPlace]=useState("");const[loading,setLoading]=useState(false);const[error,setError]=useState(false);
 const load=(lat:number,lon:number)=>{setLoading(true);setError(false);Promise.all([fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,apparent_temperature,relative_humidity_2m,wind_speed_10m&timezone=auto`).then(r=>r.ok?r.json():null),fetch(`https://api.waqi.info/feed/geo:${lat};${lon}/?token=${WAQI_TOKEN}`).then(r=>r.ok?r.json():null),fetch(`https://geocoding-api.open-meteo.com/v1/reverse?latitude=${lat}&longitude=${lon}&count=1&language=en&format=json`).then(r=>r.ok?r.json():null)]).then(([f,a,g])=>{if(!f?.current)throw Error();setWeather({temperature:Number(f.current.temperature_2m),apparent:Number(f.current.apparent_temperature),humidity:Number(f.current.relative_humidity_2m),wind:Number(f.current.wind_speed_10m),aqi:a?.status==="ok"&&a?.data?.aqi!=null?Number(a.data.aqi):null});setPlace(g?.results?.[0]?.name||"")}).catch(()=>setError(true)).finally(()=>setLoading(false))};
 const location=()=>{if(!navigator.geolocation){setError(true);return}navigator.geolocation.getCurrentPosition(p=>load(p.coords.latitude,p.coords.longitude),()=>setError(true),{enableHighAccuracy:false,timeout:8000,maximumAge:900000})};useEffect(()=>{location()},[]);
 const aqi=weather?.aqi==null?(lang==="hi"?"उपलब्ध नहीं":"Unavailable"):weather.aqi<=50?(lang==="hi"?"अच्छी हवा":"Good air"):weather.aqi<=100?(lang==="hi"?"संतोषजनक":"Moderate"):weather.aqi<=200?(lang==="hi"?"संवेदनशील लोगों के लिए सावधानी":"Unhealthy for sensitive groups"):weather.aqi<=300?(lang==="hi"?"खराब हवा":"Unhealthy"):(lang==="hi"?"बहुत खराब हवा":"Very unhealthy");
 return <main className="min-h-full bg-[#fbf8f2] pb-10"><div className="mx-auto w-full max-w-3xl px-3.5 py-4 sm:px-6 sm:py-5"><section className="relative overflow-hidden rounded-[26px] border border-amber-200/70 bg-gradient-to-br from-[#fff8e7] via-[#fffaf3] to-[#eef2ff] p-5 text-[#3b1f1f] shadow-[0_14px_35px_-24px_rgba(127,29,29,.35)] sm:p-7"><div className="pointer-events-none absolute -right-12 -top-12 h-40 w-40 rounded-full bg-amber-300/20 blur-3xl"/><div className="relative"><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.2em] text-[#9a5b13]"><Sparkles className="h-3.5 w-3.5"/>{lang==="hi"?"आज आपके लिए":"Today for you"}</div><h1 className="mt-2.5 text-[27px] font-black leading-tight sm:text-4xl">{lang==="hi"?"आपका दैनिक उपयोग":"Your daily utility"}</h1><p className="mt-2 max-w-xl text-[13px] leading-5.5 text-slate-600 sm:text-sm sm:leading-6">{lang==="hi"?"मौसम, वायु गुणवत्ता और आपकी रोज़मर्रा की उपयोगी सेवाएं—एक ही जगह।":"Weather, air quality and everyday services in one calm, useful space."}</p></div></section>
 <section className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-wider text-[#a84424]"><CloudSun className="h-4 w-4"/>Weather</div>{weather?<><div className="mt-3 flex items-end gap-2"><span className="text-[36px] font-black text-[#3b1f1f]">{Math.round(weather.temperature)}°</span><span className="pb-1 text-[13px] font-semibold text-slate-500">{place}</span></div><p className="mt-2 text-[10px] text-slate-500">Feels {Math.round(weather.apparent)}° · {weather.humidity}% humidity · {Math.round(weather.wind)} km/h wind</p></>:<div className="mt-4"><p className="text-[13px] font-semibold text-slate-700">{loading?(lang==="hi"?"स्थान की जानकारी ली जा रही है…":"Getting your location…"):(lang==="hi"?"मौसम देखने के लिए स्थान साझा करें":"Share location to see local weather")}</p><button onClick={location} className="mt-3 min-h-11 rounded-xl bg-[#a84424] px-4 py-2.5 text-[12px] font-bold text-white">{lang==="hi"?"स्थान साझा करें":"Use location"}</button></div>}</div><div className="rounded-2xl border border-indigo-100 bg-indigo-50/60 p-4 shadow-sm"><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-wider text-indigo-700"><Wind className="h-4 w-4"/>AQI</div><p className="mt-3 text-[36px] font-black text-[#3b1f1f]">{weather?.aqi==null?"—":Math.round(weather.aqi)}</p><p className="mt-1 text-[13px] font-semibold text-indigo-900">{aqi}</p><p className="mt-2 text-[10px] leading-5 text-indigo-700/70">{lang==="hi"?"वर्तमान WAQI वायु गुणवत्ता सूचकांक।":"Current WAQI air quality index."}</p></div></section>
 {error&&<div className="mt-3 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-[11px] font-semibold text-amber-900">{lang==="hi"?"स्थान या मौसम सेवा उपलब्ध नहीं है। बाद में फिर प्रयास करें।":"Location or weather service is unavailable. Try again later."}</div>}
 <section className="mt-6"><div className="mb-3"><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#a84424]">{lang==="hi"?"प्रीमियम सेवाएं":"Premium services"}</p><h2 className="mt-1 text-[15px] font-black text-[#3b1f1f]">{lang==="hi"?"जानें और जुड़ें":"Discover and connect"}</h2></div><div className="grid gap-3 sm:grid-cols-2">{cards.map(({id,icon:Icon,titleEn,titleHi,descEn,descHi,route,tone})=><button key={id} onClick={()=>navigate(route)} className="group flex min-h-[88px] items-start gap-3.5 rounded-2xl border border-slate-200 bg-white p-4 text-left shadow-sm"><span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ring-1 ${tones[tone]}`}><Icon className="h-5 w-5"/></span><span className="min-w-0 flex-1"><span className="block text-[13px] font-black text-slate-900">{lang==="hi"?titleHi:titleEn}</span><span className="mt-1 block text-[10px] leading-5 text-slate-500">{lang==="hi"?descHi:descEn}</span></span><ArrowRight className="mt-1 h-4 w-4 text-slate-300"/></button>)}</div></section>
 <section className="mt-6 grid gap-3 sm:grid-cols-2"><button onClick={()=>navigate("/blood-network")} className="flex min-h-[78px] items-center justify-between rounded-2xl border border-rose-200 bg-rose-50 p-4 text-left text-rose-950"><span><span className="block text-[13px] font-black">Blood Network</span><span className="mt-1 block text-[10px] text-rose-700">{lang==="hi"?"जरूरत हो तो अनुरोध करें या मदद करें।":"Request blood or offer help when needed."}</span></span><HeartPulse className="h-5 w-5 text-rose-700"/></button><button onClick={()=>navigate("/services")} className="flex min-h-[78px] items-center justify-between rounded-2xl border border-amber-200 bg-gradient-to-r from-[#7f1d1d] to-[#a84424] p-4 text-left text-white shadow-sm"><span><span className="block text-[13px] font-black">{lang==="hi"?"सभी सेवाएं":"All services"}</span><span className="mt-1 block text-[10px] text-orange-50">{lang==="hi"?"सभी उपलब्ध सेवाओं को देखें।":"Browse every currently available service."}</span></span><ArrowRight className="h-5 w-5"/></button></section></div></main>;
}
