import { ArrowLeft, HeartHandshake, ShieldCheck } from "lucide-react";
import { motion } from "motion/react";
import { useNavigate, useOutletContext } from "react-router-dom";

type Lang = "en" | "hi";
export default function FounderMessage() {
  const navigate = useNavigate();
  const { lang } = useOutletContext<{ lang: Lang }>();
  const hi = lang === "hi";
  return <main className="min-h-full bg-[#f8fafc] pb-10"><div className="mx-auto max-w-3xl px-3.5 py-5 sm:px-6">
    <motion.section initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} className="overflow-hidden rounded-[28px] border border-orange-200/70 bg-white shadow-[0_18px_50px_rgba(0,0,0,.07)]">
      <div className="h-1.5 bg-gradient-to-r from-[#FF9933] via-white to-[#138808]"/><div className="relative p-6 sm:p-8"><button onClick={()=>navigate(-1)} className="mb-5 inline-flex items-center gap-1 text-[11px] font-bold text-[#000080]"><ArrowLeft className="h-4 w-4"/>{hi?"वापस":"Back"}</button>
      <div className="flex flex-col gap-5 sm:flex-row sm:items-start"><motion.div whileHover={{scale:1.02}} className="relative mx-auto shrink-0 sm:mx-0"><div className="absolute inset-0 rounded-[24px] bg-gradient-to-br from-[#FF9933] via-white to-[#138808] blur-sm"/><img src="/assets/founder.png" alt="Rohit Pandit" className="relative h-48 w-40 rounded-[22px] border-2 border-white object-cover object-top shadow-xl"/></motion.div><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-[#FF9933]">RPF Seva App</p><h1 className="mt-1 text-[24px] font-black text-[#000080]">{hi?"संस्थापक का संदेश":"Founder's Message"}</h1><p className="mt-1 text-[10px] font-bold text-[#138808]">Rohit Pandit — Founder, RP Foundation</p><div className="mt-5 rounded-2xl border border-orange-100 bg-orange-50/60 p-4"><p className="text-[13px] font-bold italic leading-6 text-slate-700">{hi?'"सच्ची सेवा वही है जो समाज के सबसे कमजोर व्यक्ति तक पहुंचे और उसके जीवन में सकारात्मक परिवर्तन लाए। हम पीपुल्स यूनिवर्सिटी के साथ मिलकर इसी सेवा संकल्प को धरातल पर उतार रहे हैं।"':'"True social service is that which reaches the most vulnerable individual in society and drives tangible betterment. Together with People\'s University, we are materializing this service pledge on the ground."'}</p></div></div></div>
      <div className="mt-7 space-y-4 text-[13px] leading-6 text-slate-600"><p>{hi?"प्रिय नागरिकों और स्वयंसेवकों, हमारा लक्ष्य केवल एक संस्था चलाना नहीं है, बल्कि समाज में एक ऐसा तंत्र स्थापित करना है जहाँ हर कोई एक-दूसरे की मदद के लिए तत्पर रहे। स्वास्थ्य, शिक्षा और पर्यावरण संरक्षण के प्रति हमारी प्रतिबद्धता अडिग है।":"Dear citizens and volunteers, our vision goes beyond running an organization; it is about building an empathetic ecosystem where everyone steps forward to aid one another. Our dedication towards health, education, and nature conservation remains absolute."}</p><p>{hi?"पीपुल्स ग्रुप के नेतृत्व में हमारा अटूट विश्वास है कि शिक्षा और उन्नत स्वास्थ्य सेवा हर वर्ग की पहुँच में होनी चाहिए। मैं आप सभी से जनसेवा के इस महा-अभियान में जुड़कर स्वयंसेवक बनने और समाज के निर्माण में सहयोग देने की अपील करता हूँ।":"Backed by the institutional support of People's Group, we firmly believe that advanced healthcare and education must be within everyone's grasp. I appeal to all of you to join this collective journey as active volunteers and contributors."}</p><p>{hi?"आइए, सेवा को केवल एक गतिविधि न बनाकर अपने जीवन का संस्कार बनाएं। सेवा, समर्पण और संकल्प के साथ हम एक संवेदनशील, स्वस्थ और सशक्त समाज के निर्माण की दिशा में आगे बढ़ें।":"Let us make service not merely an activity, but a value in our lives. With Seva, Samarpan and Sankalp, let us move towards a more compassionate, healthy and empowered society."}</p></div>
      <div className="mt-7 flex items-center gap-3 rounded-2xl border border-green-100 bg-green-50/60 p-4"><ShieldCheck className="h-5 w-5 text-[#138808]"/><p className="text-[11px] font-bold leading-5 text-slate-600">{hi?"सेवा, समर्पण एंड संकल्प — यही RPF Seva App की पहचान है।":"Seva, Samarpan & Sankalp — the identity of the RPF Seva App."}</p></div>
      <motion.button whileTap={{scale:.98}} onClick={()=>navigate("/jan-seva-card")} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#138808] px-4 py-3 text-[11px] font-black text-white"><HeartHandshake className="h-4 w-4"/>{hi?"जन सेवा कार्ड से जुड़ें":"Join through Jan Seva Card"}</motion.button>
      </div></motion.section>
  </div></main>;
}
