import React,{useState}from"react";
import{ClipboardPlus,MapPin,Camera,CheckCircle,Clock,Building2,ExternalLink,FileText,ShieldCheck,Loader2}from"lucide-react";
import{useApp}from"../context/AppContext";
import{useAuth}from"../context/AuthContext";
import{useNavigate}from"react-router-dom";
import{openExternalLink}from"../utils/browser";
const portals=[
 {title:"CPGRAMS",desc:"Government of India public grievance portal.",url:"https://pgportal.gov.in/"},
 {title:"MP CM Helpline",desc:"Madhya Pradesh citizen grievance services.",url:"https://cmhelpline.mp.gov.in/"},
 {title:"National Consumer Helpline",desc:"Official consumer complaint and support portal.",url:"https://consumerhelpline.gov.in/"},
 {title:"RTI Online",desc:"Submit eligible Right to Information requests online.",url:"https://rtionline.gov.in/"}
];
export default function Grievances(){const{grievances,addGrievance}=useApp();const{user}=useAuth();const nav=useNavigate();const[tab,setTab]=useState<"new"|"track"|"official">("new");const[category,setCategory]=useState("General");const[title,setTitle]=useState("");const[description,setDescription]=useState("");const[location,setLocation]=useState("");const[imageUrl,setImageUrl]=useState("");const[submitting,setSubmitting]=useState(false);const[done,setDone]=useState("");
const submit=async()=>{if(!title.trim()||!description.trim()||!location.trim())return;setSubmitting(true);try{await addGrievance({title,description,category,location,urgency:"Medium",citizenName:user?.name||"Citizen",imageUrl} as any);setDone(`GRV-${Date.now().toString().slice(-6)}`);setTitle("");setDescription("");setLocation("");setImageUrl("")}finally{setSubmitting(false)}};
const pickImage=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(f)setImageUrl(URL.createObjectURL(f))};
return <main className="min-h-screen bg-[#fff9e9] px-4 py-5 text-slate-800"><section className="rounded-[30px] bg-gradient-to-br from-[#143d63] via-[#24557d] to-[#0f3157] p-6 text-white shadow-lg"><div className="flex items-start gap-4"><div className="rounded-2xl bg-white/15 p-3"><ClipboardPlus className="h-7 w-7"/></div><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-orange-200">Samahit Service</p><h1 className="mt-1 text-2xl font-black">Grievance</h1><p className="mt-2 text-sm leading-6 text-white/75">Report an issue, follow your submission and access official grievance services.</p></div></div></section>
<div className="mt-5 grid grid-cols-3 rounded-2xl border border-amber-100 bg-white p-1.5 shadow-sm">{([['new','Submit'],['track',`My Cases (${grievances.length})`],['official','Official Portals']] as const).map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`rounded-xl px-2 py-3 text-[10px] font-black transition ${tab===id?'bg-[#fff3d6] text-[#9a4d1b] shadow-sm':'text-slate-500'}`}>{label}</button>)}</div>
{tab==='new'&&<section className="mt-5 space-y-4">{done&&<div className="rounded-3xl border border-emerald-200 bg-emerald-50 p-5 text-center"><CheckCircle className="mx-auto h-9 w-9 text-emerald-600"/><h2 className="mt-2 font-black text-emerald-900">Grievance submitted</h2><p className="mt-1 text-xs text-emerald-700">Reference: <b>{done}</b></p></div>}<div className="rounded-[28px] border border-amber-100 bg-white p-5 shadow-sm"><p className="text-[10px] font-black uppercase tracking-[.16em] text-orange-600">New submission</p><h2 className="mt-1 text-lg font-black">Tell us what happened</h2><div className="mt-5 space-y-3"><select value={category} onChange={e=>setCategory(e.target.value)} className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-semibold"><option>General</option><option>Healthcare</option><option>Jan Seva Card</option><option>Employment</option><option>Service issue</option></select><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Short title" className="w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm"/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe the issue clearly" rows={5} className="w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm"/><label className="flex items-center gap-3 rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-4 text-sm font-bold text-slate-600"><MapPin className="h-5 w-5 text-red-500"/><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Location" className="min-w-0 flex-1 bg-transparent outline-none"/></label><label className="flex cursor-pointer items-center gap-3 rounded-2xl border border-slate-200 p-4 text-sm font-bold"><Camera className="h-5 w-5 text-[#9a4d1b]"/>Add a photo<input type="file" accept="image/*" onChange={pickImage} className="hidden"/></label>{imageUrl&&<img src={imageUrl} alt="Selected evidence" className="h-36 w-full rounded-2xl object-cover"/>}<button onClick={submit} disabled={submitting||!title||!description||!location} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-[#0f3157] px-4 py-3.5 text-sm font-black text-white disabled:opacity-50">{submitting?<Loader2 className="h-5 w-5 animate-spin"/>:<ClipboardPlus className="h-5 w-5"/>}Submit Grievance</button></div></div></section>}
{tab==='track'&&<section className="mt-5 space-y-3">{grievances.length===0?<div className="rounded-3xl border border-dashed border-slate-300 bg-white p-8 text-center"><FileText className="mx-auto h-8 w-8 text-slate-400"/><h2 className="mt-3 font-black">No grievances yet</h2><button onClick={()=>setTab('new')} className="mt-3 text-xs font-black text-orange-700">Submit your first grievance</button></div>:grievances.map((g:any,i:number)=><article key={g.id||i} className="rounded-3xl border border-slate-100 bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><div className="rounded-2xl bg-orange-50 p-2.5 text-orange-700"><Clock className="h-5 w-5"/></div><div className="min-w-0 flex-1"><p className="truncate font-black">{g.title}</p><p className="mt-1 text-xs text-slate-500">{g.category||'General'} · {g.location||'Location not provided'}</p></div><span className="rounded-full bg-amber-50 px-2 py-1 text-[9px] font-black text-amber-700">{g.status||'Submitted'}</span></div></article>)}</section>}
{tab==='official'&&<section className="mt-5 space-y-3"><div className="rounded-2xl bg-amber-50 p-4 text-xs leading-5 text-amber-900"><ShieldCheck className="mb-2 h-5 w-5"/>External portals are operated by their respective authorities. Opening one will take you to its official website.</div>{portals.map(p=><button key={p.title} onClick={()=>openExternalLink(p.url,nav,p.title)} className="flex w-full items-center gap-4 rounded-3xl border border-slate-100 bg-white p-5 text-left shadow-sm"><div className="rounded-2xl bg-blue-50 p-3 text-[#0f3157]"><Building2 className="h-6 w-6"/></div><div className="min-w-0 flex-1"><h2 className="font-black">{p.title}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{p.desc}</p></div><ExternalLink className="h-4 w-4 text-slate-400"/></button>)}</section>}</main>}
