import { useEffect, useMemo, useState } from "react";
import { ArrowRight, CloudSun, Facebook, Globe, HandHeart, HeartHandshake, HeartPulse, Instagram, Leaf, MapPin, Quote, ShieldCheck, Sparkles, Twitter, Users, Wind, Youtube } from "lucide-react";
import { useNavigate, useOutletContext } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { useApp } from "../context/AppContext";

type Lang = "en" | "hi";
type Daily = { temp: number | null; aqi: number | null; location: string };
type QuoteData = { quote: string; author: string; link?: string };
const sevaCards=[{icon:HeartPulse,title:"Care",hi:"देखभाल",text:"Be there for someone who needs support.",textHi:"किसी जरूरतमंद के लिए सहारा बनें।",tone:"rose"},{icon:Users,title:"Connect",hi:"जुड़ें",text:"Bring one person closer to a positive community.",textHi:"एक व्यक्ति को सकारात्मक समुदाय से जोड़ें।",tone:"sky"},{icon:Leaf,title:"Protect",hi:"संरक्षण",text:"Take one meaningful step for our environment.",textHi:"पर्यावरण के लिए एक सार्थक कदम उठाएं।",tone:"green"},{icon:HandHeart,title:"Share",hi:"साझा करें",text:"Share time, knowledge or encouragement.",textHi:"समय, ज्ञान या प्रोत्साहन साझा करें।",tone:"purple"}];
const socialFallback=[{platform:"twitter",label:"X",url:"https://x.com/rpfoundation15",gradient:"from-slate-700 to-black",icon:Twitter},{platform:"youtube",label:"YouTube",url:"https://www.youtube.com/@rpfoundationofficial",gradient:"from-red-500 to-red-700",icon:Youtube},{platform:"instagram",label:"Instagram",url:"https://www.instagram.com/rpfoundationofficial/",gradient:"from-pink-500 via-purple-500 to-orange-400",icon:Instagram},{platform:"facebook",label:"Facebook",url:"https://www.facebook.com/rpfofficial",gradient:"from-blue-500 to-blue-700",icon:Facebook},{platform:"website",label:"Website",url:"https://therpfoundation.org",gradient:"from-sky-400 to-blue-600",icon:Globe}];
function Skeuo({icon:Icon,tone="navy",size="md"}:{icon:any;tone?:string;size?:"sm"|"md"|"lg"}){return <span className={`skeuo-icon-surface skeuo-${tone} skeuo-size-${size}`}><Icon className="skeuo-icon" aria-hidden="true"/></span>}
export default function HomePremium(){const{lang}=useOutletContext<{lang:Lang}>();const navigate=useNavigate();const{user}=useAuth();const{settings,cmsConfig,socialLinks}=useApp();const[daily,setDaily]=useState<Daily>({temp:null,aqi:null,location:""});const[quote,setQuote]=useState<QuoteData|null>(null);const[selectedSeva,setSelectedSeva]=useState(0);const hi=lang==="hi";const name=user?.name?.trim().split(/\s+/)[0]||"";const hour=new Date().getHours();const greeting=hour<12?(hi?"सुप्रभात":"Good morning"):hour<17?(hi?"शुभ दोपहर":"Good afternoon"):(hi?"शुभ संध्या":"Good evening");
useEffect(()=>{if(!navigator.geolocation)return;navigator.geolocation.getCurrentPosition(async({coords})=>{try{const[weatherResponse,locationResponse]=await Promise.all([fetch(`/api/public/weather?lat=${coords.latitude}&lon=${coords.longitude}`).then(r=>r.ok?r.json():Promise.reject()),fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${coords.latitude}&lon=${coords.longitude}`).then(r=>r.ok?r.json():Promise.reject())]);let aqi:number|null=null;try{const a=await fetch(`https://api.waqi.info/feed/geo:${coords.latitude};${coords.longitude}/?token=83274cc3f5749b4ec7b5b6c7b9f40464debbd6b1`).then(r=>r.json());if(a?.status==="ok"&&Number.isFinite(Number(a.data?.aqi)))aqi=Number(a.data.aqi)}catch{}const address=locationResponse?.address||{};setDaily({temp:weatherResponse?.data?.current?.temperature_2m==null?null:Math.round(Number(weatherResponse.data.current.temperature_2m)),aqi,location:address.city||address.town||address.village||address.municipality||""})}catch{}},()=>undefined,{timeout:7000,maximumAge:900000})},[]);
useEffect(()=>{fetch("/api/public/quote-of-day").then(r=>r.ok?r.json():Promise.reject()).then(d=>setQuote(d.data||null)).catch(()=>setQuote(null))},[]);
const founderName=cmsConfig.founderName||"Rohit Pandit";const founderImg=settings.founderImgUrl||cmsConfig.founderImgUrl||"/assets/founder.png";const founderMessage=hi?settings.founderMessageHi:settings.founderMessageEn;const cmsSocial=(socialLinks||[]).filter(s=>["twitter","youtube","facebook","foundation_instagram"].includes(s.platform));const social=socialFallback.map(item=>{const found=cmsSocial.find(s=>item.platform==="instagram"?s.platform==="foundation_instagram":s.platform===item.platform);return{...item,url:found?.url||item.url}});const selected=useMemo(()=>sevaCards[selectedSeva],[selectedSeva]);
return <main className="min-h-full bg-[#f7f3eb] pb-12 text-slate-900 rp-tricolour-surface"><div className="mx-auto w-full max-w-3xl px-3.5 py-4 sm:px-6 sm:py-5"><section className="relative overflow-hidden rounded-[30px] border border-[#e8d7bd] bg-white/95 shadow-[0_18px_55px_rgba(73,52,25,.14)]"><div className="h-1.5 bg-gradient-to-r from-[#FF9933] via-[#FDE047] to-[#138808]"/><div className="p-5 sm:p-7"><div className="flex items-center gap-3"><div className="flex h-14 w-14 items-center justify-center overflow-hidden rounded-2xl border border-orange-200 bg-white shadow-sm"><img src="/assets/logo.png" alt="RP Foundation" className="h-full w-full object-contain"/></div><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#000080]">RP Foundation</p><p className="mt-1 text-[9px] font-bold tracking-[.12em] text-[#000080]">समाहित</p></div></div><h1 className="mt-6 text-[28px] font-black leading-tight text-[#000080] sm:text-[34px]">{greeting}{name?`, ${name}`:""}</h1><p className="mt-2 text-[13px] leading-5 text-slate-600">{hi?"जहाँ सेवा एक विचार नहीं, एक संकल्प बनकर जीवन से जुड़ती है।":"Where service becomes more than an idea — it becomes a shared commitment."}</p><button onClick={()=>navigate("/jan-seva-card")} className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-xl bg-gradient-to-r from-[#FF9933] to-[#F59E0B] px-4 py-2.5 text-[12px] font-bold text-white shadow-md active:translate-y-px"><Skeuo icon={HeartHandshake} tone="light" size="sm"/>{hi?"जन सेवा कार्ड":"Jan Seva Card"}<ArrowRight className="h-4 w-4"/></button></div></section>
<section className="mt-5 overflow-hidden rounded-[24px] border border-[#e8d7bd] bg-white shadow-[0_10px_28px_rgba(73,52,25,.08)]"><div className="grid grid-cols-3 divide-x divide-slate-100"><div className="p-4"><Skeuo icon={MapPin} tone="sky"/><p className="mt-2 text-[9px] font-black uppercase tracking-wider text-slate-400">{hi?"स्थान":"Location"}</p><p className="mt-1 line-clamp-2 text-[11px] font-black text-slate-700">{daily.location||(hi?"स्थान प्राप्त हो रहा है…":"Getting your location…")}</p></div><div className="p-4"><Skeuo icon={CloudSun} tone="sky"/><p className="mt-2 text-[9px] font-black uppercase tracking-wider text-slate-400">{hi?"मौसम":"Weather"}</p><p className="mt-1 text-[18px] font-black text-[#000080]">{daily.temp==null?"—":`${daily.temp}°`}</p></div><div className="p-4"><Skeuo icon={Wind} tone="green"/><p className="mt-2 text-[9px] font-black uppercase tracking-wider text-slate-400">AQI</p><p className="mt-1 text-[18px] font-black text-[#138808]">{daily.aqi==null?"—":daily.aqi}</p></div></div></section>
<section className="mt-3 rounded-[24px] border border-violet-100 bg-gradient-to-r from-violet-50 via-white to-pink-50 p-4 shadow-sm"><div className="flex items-start gap-3"><Skeuo icon={Quote} tone="purple"/><div className="min-w-0 flex-1"><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#7C3AED]">{hi?"आज का विचार":"Quote of the Day"}</p><p className="mt-1 text-[13px] font-bold leading-5 text-slate-700">{quote?.quote||(hi?"आज का विचार उपलब्ध नहीं है।":"Today's quote is temporarily unavailable.")}</p>{quote?.author&&<p className="mt-1 text-[10px] font-black text-slate-400">— {quote.author}</p>}</div><Sparkles className="h-4 w-4 text-[#EC4899]"/></div></section>
<section className="mt-5 rounded-[26px] border border-[#e8d7bd] bg-white p-4 shadow-[0_12px_34px_rgba(73,52,25,.10)]"><div className="flex items-center justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#FF9933]">{hi?"सेवा के छोटे कदम":"Small ways to serve"}</p><h2 className="mt-1 text-[18px] font-black text-[#000080]">{hi?selected.hi:selected.title}</h2></div><Skeuo icon={selected.icon} tone={selected.tone}/></div><p className="mt-2 text-[12px] leading-5 text-slate-600">{hi?selected.textHi:selected.text}</p><div className="mt-4 grid grid-cols-4 gap-2">{sevaCards.map((item,index)=><button key={item.title} onClick={()=>setSelectedSeva(index)} aria-label={hi?item.hi:item.title} className={`flex min-h-14 items-center justify-center rounded-2xl border transition active:scale-95 ${selectedSeva===index?"border-orange-300 bg-orange-50 shadow-inner":"border-slate-100 bg-slate-50"}`}><Skeuo icon={item.icon} tone={item.tone} size="sm"/></button>)}</div></section>
<section className="mt-5 overflow-hidden rounded-[26px] border border-[#e8d7bd] bg-gradient-to-br from-white to-[#fff7ed] shadow-[0_12px_34px_rgba(73,52,25,.10)]"><div className="p-5 sm:p-6"><div className="flex items-center gap-3"><div className="h-14 w-14 overflow-hidden rounded-2xl border-2 border-[#FF9933] bg-white shadow-md"><img src={founderImg} alt={founderName} className="h-full w-full object-cover" onError={e=>{e.currentTarget.style.visibility="hidden"}}/></div><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#FF9933]">{hi?"संस्थापक का संदेश":"Founder's Message"}</p><h2 className="mt-1 text-[17px] font-black text-[#000080]">{founderName}</h2></div></div><p className="mt-4 line-clamp-4 text-[13px] leading-6 text-slate-600">{founderMessage||(hi?"संस्थापक का संदेश शीघ्र उपलब्ध होगा।":"The founder's message will be available shortly.")}</p><button onClick={()=>navigate("/founder-speech")} className="mt-4 inline-flex items-center gap-2 text-[11px] font-black text-[#000080]">{hi?"पूरा संदेश पढ़ें":"Read full message"}<ArrowRight className="h-4 w-4"/></button></div></section>
<section className="mt-5 rounded-[26px] border border-[#e8d7bd] bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Skeuo icon={ShieldCheck} tone="green" size="sm"/><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-slate-400">RPF Foundation</p><h2 className="text-[16px] font-black text-[#000080]">{hi?"हमसे जुड़े रहें":"Stay connected"}</h2></div></div><div className="mt-4 grid grid-cols-5 gap-2">{social.map(item=><a key={item.platform} href={item.url} target="_blank" rel="noreferrer" aria-label={item.label} className={`flex min-h-12 items-center justify-center rounded-2xl bg-gradient-to-br ${item.gradient} text-white shadow-[0_5px_12px_rgba(0,0,0,.16)] transition active:translate-y-px`}><item.icon className="h-5 w-5 drop-shadow"/></a>)}</div></section></div></main>;
}
