import { useEffect, useState } from "react";
import { ArrowRight, ChevronLeft, ChevronRight, CloudSun, HeartHandshake, HeartPulse, Leaf, MapPin, Quote, Sparkles, HandHeart, BookOpen, Wind, Users, ShieldCheck } from "lucide-react";
import { motion, AnimatePresence } from "motion/react";
import { useNavigate, useOutletContext } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { useApp } from "../context/AppContext";

type Lang = "en" | "hi";
type Daily = { temp: number | null; aqi: number | null; location: string };
const quotes = [
  { en: "A small act of kindness can become someone's biggest hope.", hi: "करुणा की छोटी-सी पहल किसी की सबसे बड़ी उम्मीद बन सकती है।" },
  { en: "Seva is not an event. It is a way of living.", hi: "सेवा कोई आयोजन नहीं, जीवन जीने का एक तरीका है।" },
  { en: "When we serve together, communities grow stronger.", hi: "जब हम साथ मिलकर सेवा करते हैं, समुदाय और मजबूत बनते हैं।" },
];
const visuals = [
  { image: "https://myjaishreemahakal.in/img/food-1.png", en: "Every child's smile is a reason to serve", hi: "हर बच्चे की मुस्कान सेवा का एक कारण है" },
  { image: "https://media.assettype.com/thebridgechronicle%2F2024-10-09%2F5s41psir%2FPink-Rickshaw.jpg", en: "Women moving forward with confidence", hi: "आत्मविश्वास के साथ आगे बढ़ती महिलाएं" },
  { image: "https://files.prokerala.com/news/photos/imgs/1024/new-delhi-students-clean-up-the-yamuna-river-at-250313.jpg", en: "Youth power turns concern into action", hi: "युवा शक्ति चिंता को कार्रवाई में बदलती है" },
];
const sevaCards = [
  { icon: HeartPulse, en: "Care for people", hi: "लोगों की सेवा", textEn: "Health, blood and essential support", textHi: "स्वास्थ्य, रक्त और जरूरी सहायता", gradient: "from-[#E11D48] to-[#FB7185]" },
  { icon: BookOpen, en: "Build futures", hi: "भविष्य बनाएं", textEn: "Education, youth and opportunity", textHi: "शिक्षा, युवा और अवसर", gradient: "from-[#7C3AED] to-[#A855F7]" },
  { icon: Leaf, en: "Protect tomorrow", hi: "कल को सुरक्षित करें", textEn: "Environment and community action", textHi: "पर्यावरण और सामुदायिक पहल", gradient: "from-[#138808] to-[#22C55E]" },
];

export default function HomeV2() {
  const { lang } = useOutletContext<{ lang: Lang }>();
  const navigate = useNavigate();
  const { user } = useAuth();
  const { settings, cmsConfig } = useApp();
  const [slide, setSlide] = useState(0); const [quote, setQuote] = useState(0);
  const [daily, setDaily] = useState<Daily>({ temp: null, aqi: null, location: "" });
  const name = user?.name?.trim().split(/\s+/)[0] || ""; const h = new Date().getHours();
  const greeting = h < 12 ? (lang === "hi" ? "सुप्रभात" : "Good morning") : h < 17 ? (lang === "hi" ? "शुभ दोपहर" : "Good afternoon") : (lang === "hi" ? "शुभ संध्या" : "Good evening");
  useEffect(() => { const t = window.setInterval(() => setSlide(s => (s + 1) % visuals.length), 5200); return () => window.clearInterval(t); }, []);
  useEffect(() => { const t = window.setInterval(() => setQuote(q => (q + 1) % quotes.length), 7000); return () => window.clearInterval(t); }, []);
  useEffect(() => { if (!navigator.geolocation) return; navigator.geolocation.getCurrentPosition(async ({coords}) => { try { const [w,l] = await Promise.all([fetch(`https://api.open-meteo.com/v1/forecast?latitude=${coords.latitude}&longitude=${coords.longitude}&current=temperature_2m&timezone=auto`).then(r=>r.json()), fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${coords.latitude}&lon=${coords.longitude}`).then(r=>r.json())]); let aqi:number|null=null; try { const a=await fetch(`https://api.waqi.info/feed/geo:${coords.latitude};${coords.longitude}/?token=83274cc3f5749b4ec7b5b6c7b9f40464debbd6b1`).then(r=>r.json()); if(a?.status==="ok") aqi=Number(a.data?.aqi); } catch {} const a=l?.address||{}; const location=[a.city||a.town||a.village||a.municipality,a.state].filter(Boolean).join(", "); setDaily({temp:w?.current?Math.round(Number(w.current.temperature_2m)):null,aqi,location}); } catch {} },()=>undefined,{timeout:7000,maximumAge:900000}); },[]);
  const founderMessage = lang === "hi" ? settings.founderMessageHi : settings.founderMessageEn;
  const founderName = cmsConfig.founderName || "Rohit Pandit"; const founderImg = settings.founderImgUrl || cmsConfig.founderImgUrl || "/assets/founder.png";
  return <main className="min-h-full bg-[#f8fafc] pb-12 text-slate-900"><div className="mx-auto w-full max-w-3xl px-3.5 py-4 sm:px-6 sm:py-5">
    <motion.section initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} className="relative overflow-hidden rounded-[30px] border border-orange-200/70 bg-white shadow-[0_18px_55px_rgba(0,0,0,.08)]"><div className="h-1.5 bg-gradient-to-r from-[#FF9933] via-[#FDE047] to-[#138808]"/><div className="p-5 sm:p-7"><div className="flex items-center gap-3"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-[#FF9933] via-white to-[#138808] p-[2px] shadow-lg"><div className="flex h-full w-full items-center justify-center rounded-[14px] bg-white"><HandHeart className="h-7 w-7 text-[#000080]"/></div></div><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-[#FF9933]">RPF Seva App</p><p className="mt-1 text-[10px] font-bold tracking-[.12em] text-[#000080]">SEVA • SAMARPAN • SANKALP</p></div></div><h1 className="mt-6 text-[28px] font-black leading-tight text-[#000080] sm:text-[34px]">{greeting}{name?`, ${name}`:""}</h1><p className="mt-2 text-[13px] leading-5 text-slate-600">{lang === "hi" ? "जहाँ सेवा एक विचार नहीं, एक संकल्प बनकर जीवन से जुड़ती है।" : "Where service becomes more than an idea — it becomes a shared commitment."}</p><div className="mt-5 flex flex-wrap gap-2.5"><button onClick={()=>navigate("/jan-seva-card")} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-gradient-to-r from-[#FF9933] to-[#F59E0B] px-4 py-2.5 text-[12px] font-bold text-white shadow-md"><HeartHandshake className="h-4 w-4"/>{lang === "hi"?"जन सेवा कार्ड":"Jan Seva Card"}<ArrowRight className="h-4 w-4"/></button><button onClick={()=>navigate("/services")} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-green-200 bg-white px-4 py-2.5 text-[12px] font-bold text-[#138808]">{lang === "hi"?"सेवाएं देखें":"Explore services"}</button></div></div></motion.section>
    <section className="mt-5 overflow-hidden rounded-[24px] border border-slate-200 bg-white shadow-sm"><div className="grid grid-cols-3 divide-x divide-slate-100"><button onClick={()=>navigate("/daily")} className="p-4 text-left hover:bg-sky-50"><MapPin className="h-5 w-5 text-[#0EA5E9]"/><p className="mt-2 text-[9px] font-black uppercase tracking-wider text-slate-400">Location</p><p className="mt-1 line-clamp-2 text-[11px] font-black text-slate-700">{daily.location||"—"}</p></button><button onClick={()=>navigate("/daily")} className="p-4 text-left hover:bg-sky-50"><CloudSun className="h-5 w-5 text-[#38BDF8]"/><p className="mt-2 text-[9px] font-black uppercase tracking-wider text-slate-400">Weather</p><p className="mt-1 text-[18px] font-black text-[#000080]">{daily.temp==null?"—":`${daily.temp}°`}</p></button><button onClick={()=>navigate("/daily")} className="p-4 text-left hover:bg-green-50"><Wind className="h-5 w-5 text-[#138808]"/><p className="mt-2 text-[9px] font-black uppercase tracking-wider text-slate-400">AQI</p><p className="mt-1 text-[18px] font-black text-[#138808]">{daily.aqi==null?"—":daily.aqi}</p></button></div></section>
    <section className="mt-3 rounded-[24px] border border-violet-100 bg-gradient-to-r from-violet-50 via-white to-pink-50 p-4 shadow-sm"><div className="flex items-start gap-3"><Quote className="mt-1 h-5 w-5 shrink-0 text-[#7C3AED]"/><div className="min-w-0 flex-1"><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#7C3AED]">{lang === "hi"?"आज का विचार":"Quote of the day"}</p><p className="mt-1 text-[13px] font-bold leading-5 text-slate-700">{lang === "hi"?quotes[quote].hi:quotes[quote].en}</p></div><button onClick={()=>setQuote(q=>(q+1)%quotes.length)} className="rounded-lg bg-white p-1.5 text-slate-400 shadow-sm"><Sparkles className="h-4 w-4"/></button></div></section>
    <section className="mt-5 overflow-hidden rounded-[26px] bg-slate-900 shadow-lg"><div className="relative aspect-[16/9] overflow-hidden"><AnimatePresence mode="wait">{visuals.map((item,i)=>i===slide&&<motion.div key={item.image} initial={{opacity:0,scale:1.04}} animate={{opacity:1,scale:1}} exit={{opacity:0}} transition={{duration:.55}} className="absolute inset-0"><img src={item.image} alt="Real community service visual" className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/10 to-transparent"/><div className="absolute bottom-0 left-0 right-0 p-5 sm:p-7"><p className="text-[20px] font-black leading-tight text-white sm:text-[27px]">{lang === "hi"?item.hi:item.en}</p><p className="mt-2 text-[9px] font-bold uppercase tracking-[.2em] text-white/70">Real community visual</p></div></motion.div>)}</AnimatePresence><button onClick={()=>setSlide(s=>(s-1+visuals.length)%visuals.length)} className="absolute left-3 top-1/2 flex h-9 w-9 -translate-y-1/2 items-center justify-center rounded-full bg-white/80 text-slate-800 shadow"><ChevronLeft className="h-5 w-5"/></button><button onClick={()=>setSlide(s=>(s+1)%visuals.length)} className="absolute right-3 top-1/2 flex h-9 w-9 -translate-y-1/2 items-center justify-center rounded-full bg-white/80 text-slate-800 shadow"><ChevronRight className="h-5 w-5"/></button></div><div className="flex justify-center gap-1.5 bg-slate-900 py-3">{visuals.map((_,i)=><button key={i} onClick={()=>setSlide(i)} className={`h-1.5 rounded-full transition-all ${i===slide?"w-6 bg-white":"w-1.5 bg-white/30"}`}/>)}</div></section>
    <section className="mt-5 overflow-hidden rounded-[25px] border border-orange-200/70 bg-gradient-to-br from-orange-50 via-white to-green-50 shadow-sm"><div className="flex items-center justify-between px-5 pt-5"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#FF9933]">{lang === "hi"?"संस्थापक की बात":"From the founder"}</p><h2 className="mt-1 text-[17px] font-black text-[#000080]">{founderName}</h2></div><ShieldCheck className="h-5 w-5 text-[#138808]"/></div><div className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><img src={founderImg} alt={founderName} className="mx-auto h-36 w-32 rounded-[20px] border-2 border-white object-cover object-top shadow-lg sm:mx-0"/><div className="flex-1"><p className="text-[10px] font-bold text-[#000080]">{cmsConfig.founderDesignation || "Founder, RP FOUNDATION"}</p><p className="mt-3 line-clamp-4 text-[12px] leading-5 text-slate-600">{founderMessage || (lang === "hi"?"संस्थापक का संदेश उपलब्ध होगा।":"Founder message will appear here.")}</p><button onClick={()=>navigate("/founder-speech")} className="mt-4 inline-flex items-center gap-1 text-[11px] font-black text-[#000080]">{lang === "hi"?"पूरा संदेश पढ़ें":"Read full speech"}<ArrowRight className="h-3.5 w-3.5"/></button></div></div></section>
    <section className="mt-5 rounded-[24px] border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-3"><Users className="h-5 w-5 text-[#E11D48]"/><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#E11D48]">Seva</p><h2 className="text-[17px] font-black text-[#000080]">{lang === "hi"?"आपकी छोटी पहल, किसी की बड़ी उम्मीद":"Your small action, someone's big hope"}</h2></div></div><div className="mt-3 grid gap-2.5 sm:grid-cols-3">{sevaCards.map(({icon:Icon,en,hi,textEn,textHi,gradient})=><button key={en} onClick={()=>navigate("/services")} className="rounded-2xl border border-slate-100 bg-slate-50/70 p-4 text-left hover:shadow-md"><span className={`flex h-11 w-11 items-center justify-center rounded-xl bg-gradient-to-br ${gradient}`}><Icon className="h-5 w-5 text-white"/></span><p className="mt-3 text-[12px] font-black text-slate-800">{lang === "hi"?hi:en}</p><p className="mt-1 text-[10px] leading-4 text-slate-500">{lang === "hi"?textHi:textEn}</p><ChevronRight className="mt-3 h-4 w-4 text-slate-300"/></button>)}</div></section>
  </div></main>;
}
