import { useEffect, useState } from "react";
import { ArrowRight, ChevronLeft, ChevronRight, CloudSun, HeartHandshake, HeartPulse, Leaf, MapPin, Quote, Sparkles, HandHeart, BookOpen, Wind, Users, ShieldCheck, Instagram, Youtube, Facebook, Twitter, Globe } from "lucide-react";
import { motion, AnimatePresence } from "motion/react";
import { useNavigate, useOutletContext } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { useApp } from "../context/AppContext";

type Lang = "en" | "hi"; type Daily = { temp:number|null; aqi:number|null; location:string }; type QuoteData = { quote:string; author:string; link?:string };
const visuals = [
 {image:"https://myjaishreemahakal.in/img/food-1.png",en:"Every child's smile is a reason to serve",hi:"हर बच्चे की मुस्कान सेवा का एक कारण है"},
 {image:"https://media.assettype.com/thebridgechronicle%2F2024-10-09%2F5s41psir%2FPink-Rickshaw.jpg",en:"Women moving forward with confidence",hi:"आत्मविश्वास के साथ आगे बढ़ती महिलाएं"},
 {image:"https://files.prokerala.com/news/photos/imgs/1024/new-delhi-students-clean-up-the-yamuna-river-at-250313.jpg",en:"Youth power turns concern into action",hi:"युवा शक्ति चिंता को कार्रवाई में बदलती है"},
 {image:"https://images.unsplash.com/photo-1509099836639-18ba02c2f7a1?auto=format&fit=crop&w=1400&q=85",en:"Education opens a brighter tomorrow",hi:"शिक्षा उज्जवल कल का रास्ता खोलती है"},
 {image:"https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&w=1400&q=85",en:"Together, communities can make a difference",hi:"साथ मिलकर समुदाय बदलाव ला सकते हैं"},
 {image:"https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1400&q=85",en:"Young minds, shared purpose, real action",hi:"युवा सोच, साझा उद्देश्य और वास्तविक सेवा"}
];
const sevaCards=[
 {icon:HeartPulse,en:"Care for people",hi:"लोगों की सेवा",textEn:"Health, blood and essential support",textHi:"स्वास्थ्य, रक्त और जरूरी सहायता",gradient:"from-[#E11D48] to-[#FB7185]"},
 {icon:BookOpen,en:"Build futures",hi:"भविष्य बनाएं",textEn:"Education, youth and opportunity",textHi:"शिक्षा, युवा और अवसर",gradient:"from-[#7C3AED] to-[#A855F7]"},
 {icon:Leaf,en:"Protect tomorrow",hi:"कल को सुरक्षित करें",textEn:"Environment and community action",textHi:"पर्यावरण और सामुदायिक पहल",gradient:"from-[#138808] to-[#22C55E]"}
];
const socialFallback=[
 {platform:"twitter",label:"X",url:"https://x.com/rpfoundation15",gradient:"from-slate-800 to-black",icon:Twitter},
 {platform:"youtube",label:"YouTube",url:"https://www.youtube.com/@rpfoundationofficial",gradient:"from-red-500 to-red-700",icon:Youtube},
 {platform:"instagram",label:"Instagram",url:"https://www.instagram.com/rpfoundationofficial/",gradient:"from-pink-500 via-purple-500 to-orange-400",icon:Instagram},
 {platform:"facebook",label:"Facebook",url:"https://www.facebook.com/rpfofficial",gradient:"from-blue-500 to-blue-700",icon:Facebook},
 {platform:"website",label:"Website",url:"https://therpfoundation.org",gradient:"from-[#0EA5E9] to-[#2563EB]",icon:Globe}
];

export default function HomeV2(){
 const {lang}=useOutletContext<{lang:Lang}>(); const navigate=useNavigate(); const {user}=useAuth(); const {settings,cmsConfig,socialLinks}=useApp();
 const [slide,setSlide]=useState(0); const [daily,setDaily]=useState<Daily>({temp:null,aqi:null,location:""}); const [quote,setQuote]=useState<QuoteData|null>(null);
 const name=user?.name?.trim().split(/\s+/)[0]||""; const h=new Date().getHours(); const greeting=h<12?(lang==="hi"?"सुप्रभात":"Good morning"):h<17?(lang==="hi"?"शुभ दोपहर":"Good afternoon"):(lang==="hi"?"शुभ संध्या":"Good evening");
 useEffect(()=>{const t=window.setInterval(()=>setSlide(s=>(s+1)%visuals.length),5000);return()=>window.clearInterval(t)},[]);
 useEffect(()=>{if(!navigator.geolocation)return;navigator.geolocation.getCurrentPosition(async({coords})=>{try{const[w,l]=await Promise.all([fetch(`/api/public/weather?lat=${coords.latitude}&lon=${coords.longitude}`).then(r=>r.json()),fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${coords.latitude}&lon=${coords.longitude}`).then(r=>r.json())]);let aqi:number|null=null;try{const a=await fetch(`https://api.waqi.info/feed/geo:${coords.latitude};${coords.longitude}/?token=83274cc3f5749b4ec7b5b6c7b9f40464debbd6b1`).then(r=>r.json());if(a?.status==="ok")aqi=Number(a.data?.aqi)}catch{}const a=l?.address||{};setDaily({temp:w?.data?.current?Math.round(Number(w.data.current.temperature_2m)):null,aqi,location:[a.city||a.town||a.village||a.municipality,a.state].filter(Boolean).join(", ")})}catch{}},()=>undefined,{timeout:7000,maximumAge:900000})},[]);
 useEffect(()=>{fetch("/api/public/quote-of-day").then(r=>r.ok?r.json():Promise.reject()).then(d=>setQuote(d.data||null)).catch(()=>setQuote(null))},[]);
 const founderMessage=lang==="hi"?settings.founderMessageHi:settings.founderMessageEn; const founderName=cmsConfig.founderName||"Rohit Pandit"; const founderImg=settings.founderImgUrl||cmsConfig.founderImgUrl||"/assets/founder.png";
 const cmsSocial=(socialLinks||[]).filter(s=>["twitter","youtube","facebook","foundation_instagram"].includes(s.platform)); const social=socialFallback.map(f=>{const found=cmsSocial.find(s=>f.platform==="instagram"?s.platform==="foundation_instagram":s.platform===f.platform);return {...f,url:found?.url||f.url}});
 return <main className="min-h-full bg-[#f8fafc] pb-12 text-slate-900"><div className="mx-auto w-full max-w-3xl px-3.5 py-4 sm:px-6 sm:py-5">
 <motion.section initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} className="relative overflow-hidden rounded-[30px] border border-orange-200/70 bg-white shadow-[0_18px_55px_rgba(0,0,0,.08)]"><div className="h-1.5 bg-gradient-to-r from-[#FF9933] via-[#FDE047] to-[#138808]"/><div className="p-5 sm:p-7"><div className="flex items-center gap-3"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-[#FF9933] via-white to-[#138808] p-[2px] shadow-lg"><div className="flex h-full w-full items-center justify-center rounded-[14px] bg-white"><HandHeart className="h-7 w-7 text-[#000080]"/></div></div><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-[#FF9933]">RPF Seva App</p><p className="mt-1 text-[10px] font-bold tracking-[.12em] text-[#000080]">SEVA • SAMARPAN • SANKALP</p></div></div><h1 className="mt-6 text-[28px] font-black leading-tight text-[#000080] sm:text-[34px]">{greeting}{name?`, ${name}`:""}</h1><p className="mt-2 text-[13px] leading-5 text-slate-600">{lang==="hi"?"जहाँ सेवा एक विचार नहीं, एक संकल्प बनकर जीवन से जुड़ती है।":"Where service becomes more than an idea — it becomes a shared commitment."}</p><div className="mt-5 flex flex-wrap gap-2.5"><button onClick={()=>navigate("/jan-seva-card")} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-gradient-to-r from-[#FF9933] to-[#F59E0B] px-4 py-2.5 text-[12px] font-bold text-white shadow-md"><HeartHandshake className="h-4 w-4"/>{lang==="hi"?"जन सेवा कार्ड":"Jan Seva Card"}<ArrowRight className="h-4 w-4"/></button><button onClick={()=>navigate("/services")} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-green-200 bg-white px-4 py-2.5 text-[12px] font-bold text-[#138808]">{lang==="hi"?"सेवाएं देखें":"Explore services"}</button></div></div></motion.section>
 <section className="mt-5 overflow-hidden rounded-[24px] border border-slate-200 bg-white shadow-sm"><div className="grid grid-cols-3 divide-x divide-slate-100"><button onClick={()=>navigate("/daily")} className="p-4 text-left hover:bg-sky-50"><MapPin className="h-5 w-5 text-[#0EA5E9]"/><p className="mt-2 text-[9px] font-black uppercase tracking-wider text-slate-400">Location</p><p className="mt-1 line-clamp-2 text-[11px] font-black text-slate-700">{daily.location||"—"}</p></button><button onClick={()=>navigate("/daily")} className="p-4 text-left hover:bg-sky-50"><CloudSun className="h-5 w-5 text-[#38BDF8]"/><p className="mt-2 text-[9px] font-black uppercase tracking-wider text-slate-400">Weather</p><p className="mt-1 text-[18px] font-black text-[#000080]">{daily.temp==null?"—":`${daily.temp}°`}</p></button><button onClick={()=>navigate("/daily")} className="p-4 text-left hover:bg-green-50"><Wind className="h-5 w-5 text-[#138808]"/><p className="mt-2 text-[9px] font-black uppercase tracking-wider text-slate-400">AQI</p><p className="mt-1 text-[18px] font-black text-[#138808]">{daily.aqi==null?"—":daily.aqi}</p></button></div></section>
 <section className="mt-3 rounded-[24px] border border-violet-100 bg-gradient-to-r from-violet-50 via-white to-pink-50 p-4 shadow-sm"><div className="flex items-start gap-3"><Quote className="mt-1 h-5 w-5 shrink-0 text-[#7C3AED]"/><div className="min-w-0 flex-1"><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#7C3AED]">{lang==="hi"?"आज का विचार":"Quote of the Day"}</p><p className="mt-1 text-[13px] font-bold leading-5 text-slate-700">{quote?.quote||(lang==="hi"?"आज का विचार लोड हो रहा है…":"Today's quote is loading…")}</p>{quote?.author&&<p className="mt-1 text-[10px] font-black text-slate-400">— {quote.author}</p>}</div><Sparkles className="h-4 w-4 text-[#EC4899]"/></div></section>
 <section className="mt-5 overflow-hidden rounded-[26px] bg-slate-900 shadow-lg"><div className="relative aspect-[16/10] w-full overflow-hidden sm:aspect-[16/9]"><AnimatePresence mode="wait">{visuals.map((item,i)=>i===slide&&<motion.div key={item.image} initial={{opacity:0,scale:1.03}} animate={{opacity:1,scale:1}} exit={{opacity:0}} transition={{duration:.55}} className="absolute inset-0"><img src={item.image} alt="Real community service visual" className="block h-full w-full object-cover" loading="lazy"/><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/15 to-transparent"/><div className="absolute bottom-0 left-0 right-0 p-5 sm:p-7"><p className="max-w-xl text-[19px] font-black leading-tight text-white sm:text-[26px]">{lang==="hi"?item.hi:item.en}</p></div></motion.div>)}</AnimatePresence><button aria-label="Previous" onClick={()=>setSlide(s=>(s-1+visuals.length)%visuals.length)} className="absolute left-3 top-1/2 flex h-9 w-9 -translate-y-1/2 items-center justify-center rounded-full bg-white/85 text-slate-800 shadow"><ChevronLeft className="h-5 w-5"/></button><button aria-label="Next" onClick={()=>setSlide(s=>(s+1)%visuals.length)} className="absolute right-3 top-1/2 flex h-9 w-9 -translate-y-1/2 items-center justify-center rounded-full bg-white/85 text-slate-800 shadow"><ChevronRight className="h-5 w-5"/></button></div><div className="flex justify-center gap-1.5 bg-slate-900 py-3">{visuals.map((_,i)=><button aria-label={`Slide ${i+1}`} key={i} onClick={()=>setSlide(i)} className={`h-1.5 rounded-full transition-all ${i===slide?"w-7 bg-white":"w-1.5 bg-white/30"}`}/>)}</div></section>
 <section className="mt-5 overflow-hidden rounded-[25px] border border-orange-200/70 bg-gradient-to-br from-orange-50 via-white to-green-50 shadow-sm"><div className="flex items-center justify-between px-5 pt-5"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#FF9933]">{lang==="hi"?"संस्थापक की बात":"From the founder"}</p><h2 className="mt-1 text-[17px] font-black text-[#000080]">{founderName}</h2></div><ShieldCheck className="h-5 w-5 text-[#138808]"/></div><div className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><img src={founderImg} alt={founderName} className="mx-auto h-36 w-32 rounded-[20px] border-2 border-white object-cover object-top shadow-lg sm:mx-0"/><div className="flex-1"><p className="text-[10px] font-bold text-[#000080]">{cmsConfig.founderDesignation||"Founder, RP FOUNDATION"}</p><p className="mt-3 line-clamp-4 text-[12px] leading-5 text-slate-600">{founderMessage||(lang==="hi"?"संस्थापक का संदेश उपलब्ध होगा।":"Founder message will appear here.")}</p><button onClick={()=>navigate("/founder-speech")} className="mt-4 inline-flex items-center gap-1 text-[11px] font-black text-[#000080]">{lang==="hi"?"पूरा भाषण पढ़ें":"Read full speech"}<ArrowRight className="h-3.5 w-3.5"/></button></div></div></section>
 <section className="mt-5 rounded-[24px] border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-3"><Users className="h-5 w-5 text-[#E11D48]"/><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#E11D48]">{lang==="hi"?"सेवा की दिशाएं":"Ways to serve"}</p><h2 className="mt-1 text-[17px] font-black text-[#000080]">{lang==="hi"?"सेवा के अवसर चुनें":"Choose a way to serve"}</h2></div></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{sevaCards.map(({icon:Icon,en,hi,textEn,textHi,gradient})=><motion.button key={en} whileHover={{y:-3}} whileTap={{scale:.98}} onClick={()=>navigate("/services")} className="rounded-2xl border border-slate-100 bg-slate-50 p-4 text-left"><span className={`flex h-11 w-11 items-center justify-center rounded-xl bg-gradient-to-br ${gradient} shadow-sm`}><Icon className="h-5 w-5 text-white"/></span><p className="mt-3 text-[12px] font-black text-slate-800">{lang==="hi"?hi:en}</p><p className="mt-1 text-[10px] leading-4 text-slate-500">{lang==="hi"?textHi:textEn}</p></motion.button>)}</div></section>
 <section className="mt-5 rounded-[24px] border border-slate-200 bg-white p-4 shadow-sm"><div className="text-center"><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#000080]">RP FOUNDATION</p><p className="mt-1 text-[11px] font-bold text-slate-500">{lang==="hi"?"हमसे डिजिटल रूप से जुड़ें":"Connect with RP Foundation"}</p></div><div className="mt-4 flex items-center justify-center gap-3">{social.map(({platform,label,url,gradient:grad,icon:Icon})=><motion.a key={platform} href={url} target="_blank" rel="noreferrer" aria-label={label} whileHover={{y:-3,scale:1.05}} whileTap={{scale:.9}} className={`flex h-11 w-11 items-center justify-center rounded-2xl bg-gradient-to-br ${grad} text-white shadow-md`}><Icon className="h-5 w-5"/></motion.a>)}</div></section>
 </div></main>;
}
