import React,{useEffect,useMemo,useState}from 'react';
import {useOutletContext}from 'react-router-dom';
import {Radio,Play,Pause,Volume2,VolumeX,Search,Signal,WifiOff,ChevronRight,Music2}from 'lucide-react';
import BrandLoader from '../components/BrandLoader';
import rawChannels from '../data/akashvaniChannels.json';
import {RadioStation,useRadioPlayer} from '../context/RadioPlayerContext';

const REGIONS=[{id:'All',name:'All Stations',nameHi:'सभी स्टेशन'},{id:'Bhopal',name:'Bhopal',nameHi:'भोपाल'},{id:'MP',name:'Madhya Pradesh',nameHi:'मध्य प्रदेश'},{id:'UP',name:'Uttar Pradesh',nameHi:'उत्तर प्रदेश'},{id:'Delhi',name:'Delhi',nameHi:'दिल्ली'},{id:'Mumbai',name:'Mumbai',nameHi:'मुंबई'},{id:'Kolkata',name:'Kolkata',nameHi:'कोलकाता'},{id:'Vividh',name:'Vividh Bharati',nameHi:'विविध भारती'},{id:'Other',name:'Other Regions',nameHi:'अन्य क्षेत्र'}];
const fallbackStations=rawChannels as RadioStation[];
const validStations=(v:unknown):v is RadioStation[]=>Array.isArray(v)&&v.every((s:any)=>s&&typeof s.name==='string'&&typeof s.url==='string');
function getRegionId(name:string){const n=name.toLowerCase();if(n.includes('bhopal'))return'Bhopal';if(n.includes('delhi')||n.includes('indraprastha'))return'Delhi';if(n.includes('mumbai'))return'Mumbai';if(n.includes('kolkata'))return'Kolkata';if(n.includes('vividh')||n.includes('vbs'))return'Vividh';if(['indore','gwalior','jabalpur','chhindwara','sagar','rewa','ratlam','shahdol','balaghat'].some(c=>n.includes(c)))return'MP';if(['lucknow','kanpur','varanasi','mathura','najibabad','obra','rampur','allahabad','prayagraj','gorakhpur','agra'].some(c=>n.includes(c)))return'UP';return'Other'}
function SoundBars(){return <div className="flex h-7 items-end gap-[3px]">{[42,80,58,100,66,88,48].map((h,i)=><span key={i} className="w-[3px] rounded-full bg-[#FFB45B]" style={{height:`${h}%`,animation:`soundBar .85s ease-in-out ${i*.09}s infinite alternate`}}/>)}</div>}
function StationArt({station}:{station?:RadioStation}){return <div className="relative grid h-20 w-20 shrink-0 place-items-center overflow-hidden rounded-[24px] bg-white/10 ring-1 ring-white/10">{station?.image?<img src={station.image} alt="" className="h-full w-full object-cover" onError={e=>{e.currentTarget.style.display='none'}}/>:<Radio className="h-8 w-8 text-[#FFB45B]"/>}</div>}

export default function InternetRadio(){
 const{lang}=useOutletContext<{lang:'en'|'hi'}>();const hi=lang==='hi';
 const[stations,setStations]=useState<RadioStation[]>(fallbackStations);const[source,setSource]=useState<'server'|'fallback'>('fallback');const[search,setSearch]=useState(''),[selectedRegion,setSelectedRegion]=useState('All');
 const{station:active,playing,loading,volume,muted,error,toggle,select,setVolume,setMuted}=useRadioPlayer();
 useEffect(()=>{let cancelled=false;fetch('/api/cms',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(d=>{const configured=d?.cms?.internetRadioStations;if(!cancelled&&validStations(configured)){const ordered=[...configured].sort((a,b)=>(a.order??0)-(b.order??0));setStations(ordered);setSource('server')}}).catch(()=>undefined);return()=>{cancelled=true}},[]);
 useEffect(()=>{if(!active&&fallbackStations.length){const initial=fallbackStations.find(s=>s.name.toLowerCase()==='akashvani bhopal')||fallbackStations[0];void select(initial,false)}},[active,select]);
 const visibleStations=useMemo(()=>stations.filter(s=>s.enabled!==false),[stations]);
 const filtered=useMemo(()=>{const q=search.toLowerCase();return visibleStations.filter(s=>(selectedRegion==='All'||getRegionId(s.name)===selectedRegion)&&(!q||s.name.toLowerCase().includes(q)))},[visibleStations,search,selectedRegion]);
 return <div className="min-h-screen bg-[#F7F8FC] pb-28"><style>{`@keyframes soundBar{from{transform:scaleY(.28);opacity:.55}to{transform:scaleY(1);opacity:1}}`}</style><div className="mx-auto max-w-3xl px-4 py-5 sm:px-6">
   <header className="mb-5 flex items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-[#FF9933]"><Radio className="h-4 w-4"/><span className="text-[10px] font-black uppercase tracking-[.2em]">Samahit Radio</span></div><h1 className="mt-2 text-2xl font-black tracking-tight text-[#07133D]">{hi?'लाइव रेडियो':'Live Radio'}</h1><p className="mt-1 text-xs font-medium text-slate-500">{hi?`${visibleStations.length} स्टेशन • सुनते हुए ऐप एक्सप्लोर करें`:`${visibleStations.length} stations • keep listening while you explore`}</p></div><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#07133D] text-[#FFB45B]"><Music2 className="h-5 w-5"/></div></header>
   <section className="relative overflow-hidden rounded-[30px] bg-[#07133D] p-5 text-white shadow-[0_18px_48px_rgba(7,19,61,.22)]"><div className="absolute -right-10 -top-10 h-36 w-36 rounded-full bg-[#FF9933]/10 blur-2xl"/><div className="absolute -bottom-16 left-10 h-32 w-32 rounded-full bg-blue-500/10 blur-2xl"/><div className="relative"><div className="flex items-start gap-4"><StationArt station={active}/><div className="min-w-0 flex-1"><p className="text-[9px] font-black uppercase tracking-[.2em] text-[#FFB45B]">{playing?(hi?'अभी लाइव':'Now playing'):(hi?'तैयार':'Ready to play')}</p><h2 className="mt-2 truncate text-xl font-black">{active?.name|| (hi?'कोई स्टेशन उपलब्ध नहीं':'No station configured')}</h2><p className="mt-1 text-[11px] font-medium text-white/55">{hi?'ग्लोबल प्लेयर • ऐप में कहीं भी सुनें':'Global player • listen anywhere in Samahit'}</p></div></div>
    <div className="mt-5 flex items-center gap-3"><button onClick={()=>void toggle()} disabled={loading||!active} className="grid h-14 w-14 shrink-0 place-items-center rounded-full bg-[#FF9933] text-white shadow-lg shadow-black/20 disabled:opacity-60" aria-label={playing?'Pause radio':'Play radio'}>{loading?<BrandLoader size="sm" label={hi?'लोड हो रहा है':'Loading'}/>:playing?<Pause className="h-6 w-6 fill-current"/>:<Play className="ml-1 h-6 w-6 fill-current"/>}</button><div className="min-w-0 flex-1">{playing&&!loading?<SoundBars/>:<div className="h-7"><span className="text-[10px] font-bold uppercase tracking-wider text-white/35">{hi?'प्लेबैक रुका है':'Playback paused'}</span></div>}</div><button onClick={()=>setMuted(!muted)} className="grid h-10 w-10 place-items-center rounded-full bg-white/10 text-white/80" aria-label={muted?'Unmute':'Mute'}>{muted?<VolumeX className="h-4 w-4"/>:<Volume2 className="h-4 w-4"/>}</button></div>
    <div className="mt-4 flex items-center gap-3 rounded-2xl bg-white/[.07] px-3.5 py-3"><Signal className={`h-4 w-4 ${playing?'text-[#FFB45B]':'text-white/30'}`}/><span className="text-[10px] font-black uppercase tracking-[.14em] text-white/60">{playing?(hi?'लाइव':'Live'):(hi?'रुका हुआ':'Paused')}</span><input type="range" min="0" max="1" step=".01" value={muted?0:volume} onChange={e=>setVolume(+e.target.value)} className="ml-auto w-24 accent-[#FF9933]" aria-label="Volume"/></div>
    {error&&<div className="mt-3 flex items-center gap-2 rounded-2xl bg-red-500/15 px-3.5 py-3 text-[11px] font-bold text-red-100"><WifiOff className="h-4 w-4 shrink-0"/>{hi?'यह स्ट्रीम अभी उपलब्ध नहीं है। दूसरा स्टेशन चुनें।':error}</div>}</div></section>
   <section className="mt-6"><div className="mb-3 flex items-end justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#FF9933]">Discover</p><h3 className="mt-1 text-lg font-black text-[#07133D]">{hi?'स्टेशन खोजें':'Find a station'}</h3></div><span className="text-[11px] font-bold text-slate-400">{filtered.length} {hi?'मिले':'found'}</span></div><div className="relative"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={hi?'स्टेशन का नाम खोजें...':'Search station name...'} className="w-full rounded-2xl border border-slate-200 bg-white py-3.5 pl-11 pr-4 text-sm outline-none shadow-sm focus:border-[#07133D]"/></div><div className="mt-3 flex gap-2 overflow-x-auto pb-1 scrollbar-hide">{REGIONS.map(r=><button key={r.id} onClick={()=>setSelectedRegion(r.id)} className={`shrink-0 rounded-full px-3.5 py-2 text-[11px] font-black transition ${selectedRegion===r.id?'bg-[#07133D] text-white shadow-sm':'border border-slate-200 bg-white text-slate-500'}`}>{hi?r.nameHi:r.name}</button>)}</div></section>
   <section className="mt-5 space-y-2.5">{filtered.map(s=>{const isActive=s.name===active?.name;return <button key={`${s.name}-${s.url}`} onClick={()=>void select(s,true)} className={`group flex w-full items-center gap-3 rounded-3xl border p-3.5 text-left transition active:scale-[.99] ${isActive?'border-[#FF9933]/60 bg-[#FFF8F0] shadow-sm':'border-slate-200 bg-white hover:border-slate-300 hover:shadow-sm'}`}><div className="grid h-12 w-12 shrink-0 place-items-center overflow-hidden rounded-2xl bg-[#07133D]/[.06] text-[#07133D]">{s.image?<img src={s.image} alt="" className="h-full w-full object-cover" onError={e=>{e.currentTarget.style.display='none'}}/>:<Radio className="h-5 w-5"/>}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-black text-[#07133D]">{s.name}</p><p className="mt-1 text-[10px] font-bold text-slate-400">{isActive?(playing?(hi?'लाइव चल रहा है':'Playing live'):(hi?'चुना गया':'Selected')):(hi?'लाइव स्टेशन':'Live station')}</p></div>{isActive&&playing?<SoundBars/>:<ChevronRight className="h-4 w-4 text-slate-300 group-hover:text-[#FF9933]"/>}</button>})}{filtered.length===0&&<div className="rounded-3xl border border-dashed border-slate-300 bg-white px-6 py-14 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-slate-100 text-slate-300"><Search className="h-5 w-5"/></div><p className="mt-4 text-sm font-black text-slate-600">{hi?'कोई स्टेशन नहीं मिला':'No station found'}</p><p className="mt-1 text-xs text-slate-400">{hi?'अलग नाम या क्षेत्र से खोजें।':'Try another name or region.'}</p></div>}</section>
   {source==='fallback'&&<p className="mt-5 text-center text-[10px] font-medium text-slate-400">{hi?'सुरक्षित बैकअप स्टेशन सूची सक्रिय है':'Safe built-in backup station list active'}</p>}
 </div></div>}
