import { useState } from "react";
import { Download, Image as ImageIcon, ShieldCheck, Share2, Info } from "lucide-react";
import { useAuth } from "../context/AuthContext";
import JanSevaCard from "./JanSevaCard";

export default function JanSevaCardPage() {
  const { user } = useAuth(); const [loading,setLoading]=useState(false);
  const downloadJpeg=async()=>{setLoading(true);try{const el=document.getElementById("jan-seva-card-front");if(!el)throw new Error("Card not ready");const html2canvas=(await import("html2canvas")).default;const canvas=await html2canvas(el,{scale:3,useCORS:true,allowTaint:true,backgroundColor:"#fff",logging:false});const a=document.createElement("a");a.href=canvas.toDataURL("image/jpeg",.95);a.download=`JanSevaCard_${(user?.name||"User").replace(/\s+/g,"_")}.jpg`;a.click();}catch(e){console.error("JPEG generation failed",e);alert("Card image could not be generated. Please try again.")}finally{setLoading(false)}};
  const share=async()=>{try{if(navigator.share)await navigator.share({title:"My Jan Seva Card",text:"My digital Jan Seva Card from RP Foundation"});else await navigator.clipboard.writeText(window.location.href)}catch{}};
  return <main className="min-h-full bg-[#FAF9F6] pb-28"><div className="mx-auto max-w-3xl px-4 py-5 sm:px-6"><section className="rounded-[30px] border border-orange-100 bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-orange-50 text-[#FF9933]"><ShieldCheck className="h-5 w-5"/></div><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#B36A16]">RP Foundation identity</p><h1 className="mt-1 text-2xl font-black tracking-tight text-slate-900">Jan Seva Card</h1><p className="mt-1 text-xs leading-5 text-slate-500">Your digital service identity and access record in one place.</p></div></div><div className="mt-5 flex gap-2"><button onClick={downloadJpeg} disabled={loading} className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl bg-[#0F3157] px-4 py-3 text-xs font-black text-white disabled:opacity-60"><Download className="h-4 w-4"/>{loading?"Preparing card…":"Save card"}</button><button onClick={share} className="inline-flex h-11 w-11 items-center justify-center rounded-xl border border-slate-200 text-slate-600" aria-label="Share card"><Share2 className="h-4 w-4"/></button></div></section><section className="mt-5 overflow-hidden rounded-[30px] border border-slate-200 bg-white p-3 shadow-sm"><JanSevaCard/></section><section className="mt-5 rounded-3xl border border-blue-100 bg-blue-50/50 p-4"><div className="flex gap-3"><Info className="h-5 w-5 shrink-0 text-blue-600"/><div><h2 className="text-sm font-black text-slate-900">About your card</h2><p className="mt-1 text-[11px] leading-5 text-slate-600">Keep your profile information accurate. Card availability and benefits depend on your registration status and applicable RP Foundation programmes.</p></div></div></section></div></main>;
}
