import React,{useEffect,useMemo,useState} from 'react';
import {ArrowLeft,CheckCircle2,MapPin,User,Phone,Droplet,AlertTriangle,Check,X,Eye,EyeOff} from 'lucide-react';
import axios from 'axios';
import {Country,State,City} from 'country-state-city';

interface Props{onBack:()=>void;onComplete:(username:string,pass:string)=>void}
const BLOOD=['A+','A-','B+','B-','AB+','AB-','O+','O-'];
const DOMAINS=['gmail.com','googlemail.com','yahoo.com','yahoo.co.in','rediffmail.com','rediff.com','zoho.com','peoplesuniversity.edu.in'];
const USER=/^[a-zA-Z][a-zA-Z0-9_.]{2,19}$/;
const ageOf=(v:string)=>{if(!v)return null;const d=new Date(v+'T00:00:00'),n=new Date();let a=n.getFullYear()-d.getFullYear();if(n.getMonth()<d.getMonth()||(n.getMonth()===d.getMonth()&&n.getDate()<d.getDate()))a--;return a};

export default function VolunteerRegistrationWizard({onBack,onComplete}:Props){
 const[country,setCountry]=useState('IN'),[state,setState]=useState(''),[city,setCity]=useState(''),[pincode,setPincode]=useState(''),[area,setArea]=useState(''),[address,setAddress]=useState(''),[sansad,setSansad]=useState(''),[vidhan,setVidhan]=useState('');
 const[username,setUsername]=useState(''),[usernameStatus,setUsernameStatus]=useState<'idle'|'checking'|'available'|'taken'>('idle');
 const[fullName,setFullName]=useState(''),[fatherName,setFatherName]=useState(''),[motherName,setMotherName]=useState(''),[dob,setDob]=useState(''),[isdCode,setIsdCode]=useState('+91'),[mobile,setMobile]=useState(''),[email,setEmail]=useState(''),[bloodGroup,setBloodGroup]=useState(''),[bloodReady,setBloodReady]=useState<boolean|null>(null),[password,setPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[showPassword,setShowPassword]=useState(false);
 const[loading,setLoading]=useState(false),[error,setError]=useState(''),[submitted,setSubmitted]=useState(false),[registrationNo,setRegistrationNo]=useState('');
 const countries=useMemo(()=>Country.getAllCountries(),[]),states=useMemo(()=>State.getStatesOfCountry(country),[country]),cities=useMemo(()=>state?City.getCitiesOfState(country,state):[],[country,state]);
 const selectedCountry=Country.getCountryByCode(country),selectedState=State.getStateByCodeAndCountry(state,country),age=ageOf(dob);
 const input='mt-1 w-full p-2.5 border rounded-lg text-xs font-bold';
 const label='text-[10px] font-bold text-slate-500 uppercase';
 useEffect(()=>{setUsernameStatus('idle');const value=username.trim().toLowerCase();if(!USER.test(value))return;setUsernameStatus('checking');const t=window.setTimeout(async()=>{try{const r=await axios.get(`/api/auth/check-username?username=${encodeURIComponent(value)}`);setUsernameStatus(r.data?.available?'available':'taken')}catch{setUsernameStatus('idle')}},350);return()=>window.clearTimeout(t)},[username]);
 const changeCountry=(v:string)=>{const c=Country.getCountryByCode(v);setCountry(v);setState('');setCity('');setSansad('');setVidhan('');if(c)setIsdCode(`+${c.phonecode}`)};
 const validate=()=>{const fields:[string,unknown][]=[['User ID',username],['Full Name',fullName],['Father / Husband Name',fatherName],['Mother Name',motherName],['Date of Birth',dob],['Mobile Number',mobile],['Email',email],['Blood Group',bloodGroup],['Country',selectedCountry?.name],['State',selectedState?.name],['City',city],['Pincode',pincode],['Area / Locality',area],['Address',address],['Password',password],['Confirm Password',confirmPassword]];if(country==='IN')fields.push(['Sansad Kshetra',sansad],['Vidhan Sabha',vidhan]);const missing=fields.find(([,v])=>!String(v||'').trim());if(missing)return`This field is empty: ${missing[0]}.`;if(!USER.test(username.trim()))return'User ID must be 3-20 characters and start with a letter.';if(usernameStatus!=='available')return usernameStatus==='taken'?'This User ID is already taken.':'Please wait until User ID availability is confirmed.';if(age===null||age<16)return age!==null?'You are Minor, Not Eligible Now':'Please enter Date of Birth.';const domain=(email.toLowerCase().match(/@([^\s@]+)$/)||[])[1];if(!domain||!DOMAINS.includes(domain))return'Please use an allowed email domain.';if(bloodReady===null)return'Please select Yes or No for the Blood Donation Network.';if(password.length<8)return'Password must be at least 8 characters.';if(password!==confirmPassword)return'Passwords do not match.';return''};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');const msg=validate();if(msg)return setError(msg);setLoading(true);try{const r=await axios.post('/api/volunteer-registration/submit',{username:username.trim().toLowerCase(),full_name:fullName.trim(),father_husband_name:fatherName.trim(),mother_name:motherName.trim(),dob,isd_code:isdCode,mobile:mobile.trim(),email:email.trim(),blood_group:bloodGroup,blood_network_ready:bloodReady,country:selectedCountry?.name||country,state:selectedState?.name||'',city:city.trim(),pincode:pincode.trim(),area_locality:area.trim(),address:address.trim(),sansad_kshetra:sansad.trim(),vidhan_sabha:vidhan.trim(),password,confirm_password:confirmPassword});setRegistrationNo(r.data.registration_number||'');setSubmitted(true)}catch(err:any){setError(err.response?.data?.error||'Registration failed. Please try again.')}finally{setLoading(false)}};
 if(submitted)return <div className="flex flex-col min-h-screen bg-white rounded-3xl overflow-hidden shadow-2xl border border-slate-200"><div className="bg-[#0B1E3F] text-white p-4 flex items-center justify-between"><div className="w-8"/><h2 className="font-black text-sm">Registration Successful</h2><button onClick={onBack}><X className="w-5 h-5"/></button></div><div className="flex-1 flex flex-col items-center justify-center p-6 text-center gap-4"><CheckCircle2 className="w-16 h-16 text-green-600"/><h3 className="text-xl font-black text-slate-800">Welcome to RP Foundation</h3><div className="w-full bg-slate-900 text-white rounded-2xl p-5"><p className="text-[10px] uppercase tracking-widest text-slate-400">User ID / Login ID</p><p className="text-lg font-black text-[#FF9933] mt-1">{username}</p><p className="text-[10px] uppercase tracking-widest text-slate-400 mt-4">Volunteer Registration No.</p><p className="text-sm font-black mt-1">{registrationNo}</p></div><p className="text-xs text-slate-500">Keep your User ID and Registration Number safe.</p><button onClick={()=>onComplete(username,password)} className="w-full py-3.5 bg-[#000080] text-white rounded-xl text-xs font-black uppercase">Continue to Login</button></div></div>;
 return <div className="flex flex-col min-h-screen bg-white rounded-3xl overflow-hidden shadow-2xl border border-slate-200"><div className="bg-[#0B1E3F] text-white p-4 flex items-center justify-between sticky top-0 z-10"><button onClick={onBack}><ArrowLeft className="w-5 h-5"/></button><div className="text-center"><h2 className="font-black text-sm">Volunteer Registration</h2><p className="text-[9px] text-slate-300">All fields are mandatory</p></div><div className="w-5"/></div><form onSubmit={submit} noValidate className="flex-1 overflow-y-auto p-5 space-y-6 pb-10">{error&&<div className="p-3 bg-red-50 border border-red-200 text-red-700 rounded-xl text-xs font-bold flex gap-2"><AlertTriangle className="w-4 h-4 shrink-0"/>{error}</div>}
 <section className="space-y-4"><h3 className="font-black text-sm flex gap-2 border-b pb-2"><User className="w-4 h-4"/>Login Identity</h3><label className={label}>User ID<input required value={username} onChange={e=>setUsername(e.target.value.replace(/\s/g,''))} className={input}/>{usernameStatus==='checking'&&<span className="block mt-1 normal-case">Checking availability...</span>}{usernameStatus==='available'&&<span className="flex gap-1 mt-1 text-green-700 normal-case"><Check className="w-3 h-3"/>Available</span>}{usernameStatus==='taken'&&<span className="block mt-1 text-red-600 normal-case">Already taken</span>}</label></section>
 <section className="space-y-4"><h3 className="font-black text-sm flex gap-2 border-b pb-2"><MapPin className="w-4 h-4"/>Address & Administrative Details</h3><p className="text-[10px] text-slate-500">GPS location is not collected during registration. Field-work location can be requested later only when needed.</p><div className="grid grid-cols-2 gap-3"><label className={label}>Country<select value={country} onChange={e=>changeCountry(e.target.value)} className={input}>{countries.map(c=><option key={c.isoCode} value={c.isoCode}>{c.name}</option>)}</select></label><label className={label}>State<select required value={state} onChange={e=>setState(e.target.value)} className={input}><option value="">Select</option>{states.map(s=><option key={s.isoCode} value={s.isoCode}>{s.name}</option>)}</select></label><label className={label}>City<select required value={city} onChange={e=>setCity(e.target.value)} className={input}><option value="">Select</option>{cities.map(c=><option key={`${c.name}-${c.latitude}`} value={c.name}>{c.name}</option>)}</select></label><label className={label}>Pincode<input required value={pincode} onChange={e=>setPincode(e.target.value)} className={input}/></label></div><label className={label}>Area / Locality<input required value={area} onChange={e=>setArea(e.target.value)} className={input}/></label>{country==='IN'&&<div className="grid grid-cols-2 gap-3"><label className={label}>Sansad Kshetra<input required value={sansad} onChange={e=>setSansad(e.target.value)} className={input}/></label><label className={label}>Vidhan Sabha<input required value={vidhan} onChange={e=>setVidhan(e.target.value)} className={input}/></label></div>}<label className={label}>Full Address<textarea required value={address} onChange={e=>setAddress(e.target.value)} rows={2} className={`${input} resize-none`}/></label></section>
 <section className="space-y-4"><h3 className="font-black text-sm border-b pb-2">Personal Details</h3><label className={label}>Full Name<input required value={fullName} onChange={e=>setFullName(e.target.value)} className={input}/></label><div className="grid grid-cols-2 gap-3"><label className={label}>Father / Husband Name<input required value={fatherName} onChange={e=>setFatherName(e.target.value)} className={input}/></label><label className={label}>Mother Name<input required value={motherName} onChange={e=>setMotherName(e.target.value)} className={input}/></label><label className={label}>Date of Birth<input required type="date" value={dob} onChange={e=>setDob(e.target.value)} className={input}/></label><label className={label}>Blood Group<select required value={bloodGroup} onChange={e=>setBloodGroup(e.target.value)} className={input}><option value="">Select</option>{BLOOD.map(x=><option key={x}>{x}</option>)}</select></label></div></section>
 <section className="space-y-4"><h3 className="font-black text-sm flex gap-2 border-b pb-2"><Phone className="w-4 h-4"/>Contact</h3><div className="grid grid-cols-[110px_1fr] gap-2"><label className={label}>ISD<select value={isdCode} onChange={e=>setIsdCode(e.target.value)} className={input}>{countries.map(c=><option key={`${c.isoCode}-${c.phonecode}`} value={`+${c.phonecode}`}>+{c.phonecode} ({c.isoCode})</option>)}</select></label><label className={label}>Mobile<input required value={mobile} onChange={e=>setMobile(e.target.value.replace(/\D/g,''))} className={input}/></label></div><label className={label}>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className={input}/></label><div className="p-3 rounded-xl border"><div className="flex items-center gap-2 text-xs font-black"><Droplet className="w-4 h-4 text-red-600"/>Ready to join Blood Donation Network?</div><div className="grid grid-cols-2 gap-3 mt-3"><button type="button" onClick={()=>setBloodReady(true)} className={`py-3 rounded-xl text-xs font-black ${bloodReady===true?'bg-emerald-600 text-white':'bg-slate-100'}`}>Yes</button><button type="button" onClick={()=>setBloodReady(false)} className={`py-3 rounded-xl text-xs font-black ${bloodReady===false?'bg-rose-600 text-white':'bg-slate-100'}`}>No</button></div></div></section>
 <section className="space-y-4"><h3 className="font-black text-sm border-b pb-2">Password</h3><label className={label}>Create Password<div className="relative"><input required type={showPassword?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} className={input}/><button type="button" onClick={()=>setShowPassword(!showPassword)} className="absolute right-2 top-3">{showPassword?<EyeOff className="w-4 h-4"/>:<Eye className="w-4 h-4"/>}</button></div></label><label className={label}>Confirm Password<input required type={showPassword?'text':'password'} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} className={input}/></label></section>
 <button disabled={loading} className="w-full py-4 bg-[#000080] disabled:opacity-60 text-white rounded-xl text-xs font-black uppercase">{loading?'Submitting...':'Submit Volunteer Registration'}</button></form></div>;
}
