import React,{createContext,useCallback,useContext,useEffect,useRef,useState}from 'react';

export type RadioStation={name:string;url:string;image:string;page:string;enabled?:boolean;order?:number};
type RadioPlayerState={station:RadioStation|null;playing:boolean;loading:boolean;volume:number;muted:boolean;error:string;play:(station?:RadioStation|null)=>Promise<void>;pause:()=>void;toggle:()=>Promise<void>;select:(station:RadioStation,autoplay?:boolean)=>Promise<void>;setVolume:(value:number)=>void;setMuted:(value:boolean)=>void};
const RadioPlayerContext=createContext<RadioPlayerState|null>(null);
export function RadioPlayerProvider({children}:{children:React.ReactNode}){const audioRef=useRef<HTMLAudioElement|null>(null);const hlsRef=useRef<any>(null);const retryRef=useRef(0);const[station,setStation]=useState<RadioStation|null>(null);const[playing,setPlaying]=useState(false);const[loading,setLoading]=useState(false);const[volume,setVolumeState]=useState(.85);const[muted,setMutedState]=useState(false);const[error,setError]=useState('');
const cleanup=useCallback(()=>{if(hlsRef.current){hlsRef.current.destroy();hlsRef.current=null}const a=audioRef.current;if(a){a.pause();a.removeAttribute('src');a.load()}},[]);
const pause=useCallback(()=>{audioRef.current?.pause();setPlaying(false)},[]);
const play=useCallback(async(target?:RadioStation|null)=>{const next=target||station;const audio=audioRef.current;if(!next||!audio)return;setStation(next);setError('');setLoading(true);retryRef.current=0;try{cleanup();audio.volume=volume;audio.muted=muted;if(/\.m3u8(?:\?|$)/i.test(next.url)){const Hls=(await import('hls.js')).default;if(Hls.isSupported()){const hls=new Hls({lowLatencyMode:true,maxBufferLength:8,backBufferLength:15,enableWorker:true,manifestLoadingMaxRetry:2,levelLoadingMaxRetry:2});hlsRef.current=hls;hls.loadSource(next.url);hls.attachMedia(audio);await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('timeout')),12000);hls.on(Hls.Events.MANIFEST_PARSED,()=>{clearTimeout(timer);resolve()});hls.on(Hls.Events.ERROR,(_:any,data:any)=>{if(data.fatal){clearTimeout(timer);reject(new Error('stream'))}})});await audio.play()}else if(audio.canPlayType('application/vnd.apple.mpegurl')){audio.src=next.url;await audio.play()}else throw new Error('HLS unsupported')}else{audio.src=next.url;await audio.play()}setPlaying(true)}catch{setPlaying(false);setError('Stream is unavailable right now. Please try another station.')}finally{setLoading(false)}},[cleanup,station,volume,muted]);
const select=useCallback(async(next:RadioStation,autoplay=true)=>{setStation(next);setError('');if(autoplay)await play(next)},[play]);
const toggle=useCallback(async()=>{if(playing){pause();return}await play()},[playing,pause,play]);
const setVolume=useCallback((value:number)=>{const v=Math.max(0,Math.min(1,value));setVolumeState(v);if(audioRef.current)audioRef.current.volume=v;if(v>0){setMutedState(false);if(audioRef.current)audioRef.current.muted=false}},[]);
const setMuted=useCallback((value:boolean)=>{setMutedState(value);if(audioRef.current)audioRef.current.muted=value},[]);
useEffect(()=>{const audio=audioRef.current;if(!audio)return;const onPlay=()=>{setPlaying(true);setError('')};const onPause=()=>setPlaying(false);const onError=()=>{if(retryRef.current<1&&station){retryRef.current+=1;setTimeout(()=>void play(station),700)}};audio.addEventListener('play',onPlay);audio.addEventListener('pause',onPause);audio.addEventListener('error',onError);return()=>{audio.removeEventListener('play',onPlay);audio.removeEventListener('pause',onPause);audio.removeEventListener('error',onError)}},[station,play]);
useEffect(()=>()=>cleanup(),[cleanup]);
return <RadioPlayerContext.Provider value={{station,playing,loading,volume,muted,error,play,pause,toggle,select,setVolume,setMuted}}><audio ref={audioRef} preload="none" playsInline/>{children}</RadioPlayerContext.Provider>}
export function useRadioPlayer(){const ctx=useContext(RadioPlayerContext);if(!ctx)throw new Error('useRadioPlayer must be used inside RadioPlayerProvider');return ctx}
