import React,{useState} from "react";
import {Outlet,useNavigate,useLocation} from "react-router-dom";
import {ArrowLeft,User,Compass,Bell,Search,Globe,Heart,HeartHandshake} from "lucide-react";
import {useAuth} from "../context/AuthContext";import {useApp} from "../context/AppContext";
export default function MainLayout(){const navigate=useNavigate();const location=useLocation();const{language,setLanguage,user}=useAuth();const{notifications,globalSettings}=useApp();const isAdmin=user?.role==="admin"||user?.role==="super_admin";const unread=notifications?.filter(n=>!n.read).length||0;const[guest,setGuest]=useState(false);React.useEffect(()=>{if(isAdmin&&!location.pathname.startsWith("/admin"))navigate("/admin")},[isAdmin,location.pathname,navigate]);if(isAdmin)return <div className="min-h-screen w-full bg-[#fbf8f2] font-sans text-slate-900"><Outlet context={{lang:language}}/></div>;
 const nav=(p:string)=>{if(user?.role==="guest"&&(p==="/services"||p==="/community"||p==="/notifications")){setGuest(true);return}navigate(p)};const roots=["/","/services","/community","/notifications","/profile"];const root=roots.includes(location.pathname);const items=[{path:"/",en:"Home",hi:"होम",icon:Compass},{path:"/services",en:"Explore",hi:"खोजें",icon:Search},{path:"/notifications",en:"Activity",hi:"गतिविधि",icon:Bell},{path:"/community",en:"Impact",hi:"प्रभाव",icon:Heart},{path:"/profile",en:"Me",hi:"मैं",icon:User}];
 return <div className="min-h-screen w-full overflow-hidden bg-[#fbf8f2] font-sans text-slate-900 selection:bg-orange-100 selection:text-[#7f1d1d]"><header className="sticky top-0 z-40 w-full border-b border-amber-100/80 bg-white/95 px-3.5 pt-safe-header backdrop-blur-xl"><div className="mx-auto flex h-14 max-w-3xl items-center justify-between sm:h-16 sm:px-1"><div className="flex min-w-0 items-center gap-2.5">{!root?<button onClick={()=>navigate(-1)} aria-label="Go back" className="flex h-10 w-10 items-center justify-center rounded-full text-[#7f1d1d] hover:bg-orange-50"><ArrowLeft className="h-5 w-5"/></button>:<div className="flex h-9 w-9 items-center justify-center overflow-hidden rounded-xl border border-amber-200 bg-white shadow-sm sm:h-10 sm:w-10"><img src={globalSettings?.logo_image||"/assets/logo.png"} alt="RP Foundation" className="h-full w-full object-contain"/></div>}<div className="min-w-0"><h1 className="truncate text-[14px] font-semibold tracking-[-0.02em] text-[#3b1f1f] sm:text-[15px]">RP Foundation</h1><p className="truncate text-[9px] font-medium tracking-[.08em] text-slate-400">COMMUNITY • SERVICE • IMPACT</p></div></div><div className="flex items-center gap-0.5"><button onClick={()=>setLanguage(language==="hi"?"en":"hi")} className="flex h-10 w-10 items-center justify-center rounded-full text-indigo-700 hover:bg-indigo-50"><Globe className="h-[19px] w-[19px]"/></button><button onClick={()=>nav("/notifications")} className="relative flex h-10 w-10 items-center justify-center rounded-full text-[#a84424] hover:bg-orange-50"><Bell className="h-[19px] w-[19px]"/>{unread>0&&<span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-rose-500 ring-2 ring-white"/>}</button><button onClick={()=>nav("/profile")} className="flex h-9 w-9 items-center justify-center rounded-full border border-amber-200 bg-amber-50 text-[#7f1d1d]"><User className="h-[17px] w-[17px]"/></button></div></div></header>
 <main className="min-h-0 w-full overflow-x-hidden bg-[#fbf8f2] pb-[calc(5.25rem+env(safe-area-inset-bottom))]"><div className="mx-auto w-full max-w-3xl"><Outlet context={{lang:language}}/></div></main>
 {(location.pathname==="/"||location.pathname==="/services")&&<button onClick={()=>nav("/donations")} aria-label="Donate" className="fixed bottom-[calc(4.75rem+env(safe-area-inset-bottom))] right-3.5 z-40 flex h-12 w-12 items-center justify-center rounded-full bg-[#a84424] text-white shadow-lg shadow-orange-900/20"><HeartHandshake className="h-5 w-5"/></button>}
 <nav className="fixed inset-x-0 bottom-0 z-50 border-t border-amber-100/80 bg-white/96 px-1 pt-1 pb-[calc(.35rem+env(safe-area-inset-bottom))] shadow-[0_-8px_30px_-20px_rgba(127,29,29,.22)] backdrop-blur-xl"><div className="mx-auto flex max-w-3xl items-center justify-around">{items.map(({path,en,hi,icon:Icon})=>{const active=location.pathname===path;return <button key={path} onClick={()=>nav(path)} className={`relative flex min-h-12 w-1/5 flex-col items-center justify-center gap-1 rounded-xl px-1 text-[10px] font-medium ${active?"text-[#a84424]":"text-slate-400 hover:text-indigo-700"}`}><Icon className="h-[19px] w-[19px]"/><span>{language==="hi"?hi:en}</span>{active&&<span className="absolute bottom-0 h-0.5 w-5 rounded-full bg-[#a84424]"/>}{path==="/notifications"&&unread>0&&<span className="absolute right-[calc(50%-0.8rem)] top-1 h-1.5 w-1.5 rounded-full bg-rose-500 ring-2 ring-white"/>}</button>})}</div></nav>
 {guest&&<div className="fixed inset-0 z-[100] flex items-end justify-center bg-[#4c1d1d]/25 p-4 backdrop-blur-sm sm:items-center"><div className="w-full max-w-sm rounded-3xl border border-amber-100 bg-white p-6 shadow-2xl"><div className="mb-5 flex h-11 w-11 items-center justify-center rounded-2xl bg-orange-50 text-[#a84424]"><User className="h-5 w-5"/></div><h2 className="text-lg font-semibold text-[#3b1f1f]">{language==="hi"?"पहले साइन इन करें":"Sign in to continue"}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{language==="hi"?"इस सुविधा का उपयोग करने के लिए अपने खाते में साइन इन करें।":"Sign in to access your personal community features."}</p><div className="mt-6 flex gap-2"><button onClick={()=>setGuest(false)} className="flex-1 rounded-xl border border-slate-200 px-4 py-3 text-sm text-slate-700">Close</button><button onClick={()=>{setGuest(false);navigate("/login")}} className="flex-1 rounded-xl bg-[#a84424] px-4 py-3 text-sm font-semibold text-white">Sign in</button></div></div></div>}
 </div>}
